// src/lib/components/tournament/Schedule.svelte
<script lang="ts">
	import FullScheduleModal from './FullScheduleModal.svelte';
	import { tournament } from '$lib/stores/tournament.svelte';
	import { showToast, cn } from '$lib/shared/utils';
	import { launchConfetti } from '$lib/tournament/confetti';
	import { formatEstimatedRoundStart } from '$lib/tournament/ui/components/scheduleTiming';
	import { printTournamentSchedule } from '$lib/tournament/ui/setup/exportShare';
	import { getCourtDisplayName } from '$lib/tournament/courtNames';
	import { parseScoreInput, validateRoundScores } from '$lib/tournament/scoring/scoreValidation';
	import { fade, scale } from 'svelte/transition';

	const ts = $derived(tournament.state);
	const schedule = $derived(ts.schedule);
	const format = $derived(ts.format);
	const showCourtSvg = $derived(format !== 'division');
	const allRounds = $derived(ts.allRounds);
	const roundStartedAt = $derived(ts.roundStartedAt);

	let isFullScheduleOpen = $state(false);
	let selectedRoundIdx = $state(0);
	let activeScoreSelector = $state<{ rIdx: number; mIdx: number; team: 1 | 2 } | null>(null);

	// Sync selected round when a new round is generated or active round updates
	$effect(() => {
		if (schedule.length > 0) {
			selectedRoundIdx = schedule.length - 1;
		}
	});

	function getCourtName(courtNum: number, division?: string | null) {
		return getCourtDisplayName(ts, courtNum, division);
	}

	const nextRoundPreview = $derived(
		format === 'division' && allRounds && schedule.length < allRounds.length
			? allRounds[schedule.length]
			: null
	);

	function handleScoreChange(rIdx: number, mIdx: number, team: 1 | 2, val: number | null) {
		const newSchedule = [...schedule];
		const match = { ...newSchedule[rIdx].matches[mIdx] };

		if (val == null) {
			if (team === 1) match.score1 = undefined;
			else match.score2 = undefined;
			newSchedule[rIdx].matches[mIdx] = match;
			tournament.updateField('schedule', newSchedule);
			return;
		}

		if (team === 1) match.score1 = val;
		else match.score2 = val;

		if (ts.scoringMode === 'total') {
			if (team === 1) match.score2 = ts.pointsPerMatch - val;
			else match.score1 = ts.pointsPerMatch - val;
		} else if (ts.scoringMode === 'race') {
			if (val < ts.pointsPerMatch) {
				if (team === 1) match.score2 = ts.pointsPerMatch;
				else match.score1 = ts.pointsPerMatch;
			}
		}

		newSchedule[rIdx].matches[mIdx] = match;
		tournament.updateField('schedule', newSchedule);
	}

	function handleCompleteRound(rIdx: number) {
		const round = schedule[rIdx];
		const errors = validateRoundScores(round, {
			scoringMode: ts.scoringMode,
			pointsPerMatch: ts.pointsPerMatch
		});
		if (errors.length > 0) {
			showToast(errors[0], 'error');
			return;
		}
		if (round?.name === 'Final') {
			launchConfetti();
		}
		const result = tournament.completeRound();
		if (!result.ok) {
			showToast(result.errors?.[0] || 'Invalid round', 'error');
			return;
		}
		showToast(`Round ${rIdx + 1} Completed!`, 'success');
	}

	function handleEditRound(rIdx: number, mIdx: number) {
		tournament.editRound(rIdx, mIdx);
		showToast(`Round ${rIdx + 1} re-opened. Match ${mIdx + 1} is ready to edit`, 'info');
	}

	function handleToggleBye(playerId: string) {
		const newByes = ts.manualByes.includes(playerId)
			? ts.manualByes.filter((id) => id !== playerId)
			: [...ts.manualByes, playerId];
		tournament.updateField('manualByes', newByes);
	}

	function getRoundMetaLabel(round: any, idx: number) {
		if (!round.completed) {
			return `EST. START: ${formatEstimatedRoundStart(ts, idx)}`;
		}
		if (round.durationSeconds == null) {
			return 'FINISHED';
		}
		return `FINISHED · ${Math.round(round.durationSeconds / 60)} MIN`;
	}

	function getMatchWinner(match: any) {
		if (match.score1 == null || match.score2 == null) return null;
		return match.score1 > match.score2 ? 1 : 2;
	}

	function handlePrintSchedule() {
		printTournamentSchedule(ts as any);
	}
</script>

<div class="relative z-10 w-full font-sans select-none">
	<!-- Round Switcher Tabs (Minimal & Borderless) -->
	<div
		class="mb-8 flex scrollbar-none items-center gap-2 overflow-x-auto border-b border-border/10 pb-4"
	>
		{#each schedule as round, idx}
			{@const isActiveRound = idx === schedule.length - 1}
			{@const isSelected = idx === selectedRoundIdx}
			<button
				type="button"
				onclick={() => (selectedRoundIdx = idx)}
				class={cn(
					'flex min-h-[44px] shrink-0 cursor-pointer items-center gap-2 rounded-lg px-4 py-2.5 text-xs font-black tracking-wider uppercase transition-all duration-200',
					isSelected
						? 'bg-foreground text-background shadow-sm shadow-foreground/5'
						: 'border border-border/10 bg-foreground/[0.02] text-foreground/45 hover:bg-foreground/[0.05] hover:text-foreground'
				)}
			>
				{round.name || `Round ${round.number}`}
				{#if isActiveRound && !round.completed}
					<span class="inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-accent"></span>
				{:else if round.completed}
					<span class="inline-block text-[10px] font-bold text-[#34C759]">✓</span>
				{/if}
			</button>
		{/each}
		{#if schedule.length > 0}
			<button
				type="button"
				onclick={handlePrintSchedule}
				class="ml-auto min-h-[44px] shrink-0 cursor-pointer rounded-lg border border-border/10 bg-foreground/[0.02] px-4 py-2.5 text-xs font-black tracking-wider text-foreground/45 uppercase transition-all duration-200 hover:bg-foreground/[0.05] hover:text-foreground"
			>
				Print schedule
			</button>
		{/if}
	</div>

	{#if schedule[selectedRoundIdx]}
		{@const round = schedule[selectedRoundIdx]}
		{@const idx = selectedRoundIdx}
		{@const isActiveRound = idx === schedule.length - 1}

		<div class="animate-fade-in space-y-8" transition:fade={{ duration: 250 }}>
			<!-- Round Info Banner -->
			<div
				class="flex flex-col items-start justify-between gap-4 border-b border-border/20 pb-4 sm:flex-row sm:items-center"
			>
				<div class="space-y-1">
					<div class="flex items-center gap-3">
						<h3
							class="font-display text-3xl leading-none font-black tracking-normal text-foreground"
						>
							{round.name || `Round ${round.number}`}
						</h3>

						{#if !round.completed && !roundStartedAt && isActiveRound}
							<button
								type="button"
								class="flex min-h-[44px] cursor-pointer items-center gap-1.5 rounded-md bg-foreground px-3 py-1.5 text-[11px] font-black tracking-wider text-background uppercase shadow-sm transition-all active:scale-95"
								onclick={(e) => {
									e.stopPropagation();
									tournament.updateField('roundStartedAt', Date.now());
								}}
							>
								▶ START ROUND
							</button>
						{/if}
					</div>
					<p
						class="text-[11px] leading-none font-black tracking-wider text-foreground/35 uppercase"
					>
						{getRoundMetaLabel(round, idx)}
					</p>
				</div>

				<div class="flex items-center gap-2">
					{#if round.completed}
						<span
							class="flex items-center gap-2 rounded-md border border-[#34C759]/10 bg-[#34C759]/5 px-3 py-1.5 text-xs font-black tracking-wider text-[#34C759] uppercase"
						>
							<div class="h-1.5 w-1.5 rounded-full bg-[#34C759]"></div>
							COMPLETED
						</span>
					{:else if roundStartedAt && isActiveRound}
						<span
							class="flex items-center gap-2 rounded-md border border-accent/15 bg-accent/5 px-3 py-1.5 text-xs font-black tracking-wider text-accent uppercase"
						>
							<div class="h-1.5 w-1.5 rounded-full bg-accent"></div>
							LIVE NOW
						</span>
					{:else}
						<span
							class="flex items-center gap-2 rounded-md border border-border/10 bg-foreground/[0.02] px-3 py-1.5 text-xs font-black tracking-wider text-foreground/40 uppercase"
						>
							<div class="h-1.5 w-1.5 rounded-full bg-foreground/20"></div>
							STANDBY
						</span>
					{/if}
				</div>
			</div>

			<!-- Resting Players (if any) -->
			{#if showCourtSvg && round.byes && round.byes.length > 0}
				<div class="flex flex-wrap items-center gap-2 rounded-xl border border-border/10 bg-foreground/[0.02] p-4 text-xs">
					<span class="font-black tracking-wider text-foreground/45 uppercase mr-2 flex items-center gap-1.5">
						Resting Players:
					</span>
					<div class="flex flex-wrap items-center gap-x-2.5 gap-y-1.5">
						{#each round.byes as p, bIdx}
							{#if bIdx > 0}
								<span class="text-foreground/15 select-none">•</span>
							{/if}
							<span class="rounded border border-border/5 bg-foreground/[0.04] px-2 py-0.5 font-semibold text-foreground">
								{p.name}
							</span>
						{/each}
					</div>
				</div>
			{/if}

			<!-- Active Matches Display (Television Scoreboard Grid) -->
			<div
				class={cn('grid', showCourtSvg ? 'gap-6' : 'gap-3')}
				style="grid-template-columns: {ts.gridColumns > 0
					? `repeat(${ts.gridColumns}, minmax(0, 1fr))`
					: 'repeat(auto-fit, minmax(min(100%, 320px), 1fr))'}; font-size: {ts.textSize}%;"
			>
				{#each round.matches as match, mIdx}
					{@const isSelectedMatch = ts.ui.selectedMatchId === `round-${idx}-match-${mIdx}`}
					{@const matchDivision =
						format === 'division' ? (match.team1[0] as any)?.division || 'A' : null}
					{@const winner = getMatchWinner(match)}

					{#if showCourtSvg}
						<div class="flex flex-col">
							<!-- Court Header Outside (Only for Court SVG mode) -->
							<div class="mb-2 flex items-center justify-between text-xs font-black tracking-wider text-foreground/50 uppercase">
								<div class="flex items-center gap-2">
									{#if matchDivision}
										<span class="text-accent">DIV {matchDivision}</span>
										<span class="text-foreground/15">•</span>
									{/if}
									<span class="text-foreground/90 font-black text-sm tracking-normal">{getCourtName(match.court, matchDivision)}</span>
								</div>
							</div>

							<!-- Court SVG Card -->
							<div
								class={cn(
									'relative overflow-hidden rounded-xl border border-border/10 p-6 shadow-lg shadow-black/10 bg-[#3888FF]',
									isSelectedMatch && 'z-10 ring-2 ring-accent/60 shadow-xl'
								)}
							>
								<!-- Court Background SVG (Inlined for reliability) -->
								<div class="absolute inset-0 pointer-events-none z-0">
									<svg class="h-full w-full" viewBox="0 0 720 360" preserveAspectRatio="none" fill="none" xmlns="http://www.w3.org/2000/svg">
										<rect width="720" height="360" fill="#3888FF"/>
										<rect x="4" y="4" width="712" height="352" stroke="white" stroke-width="3" fill="none" stroke-opacity="0.9"/>
										<line x1="110" y1="4" x2="110" y2="356" stroke="white" stroke-width="2.5" stroke-opacity="0.85"/>
										<line x1="610" y1="4" x2="610" y2="356" stroke="white" stroke-width="2.5" stroke-opacity="0.85"/>
										<line x1="110" y1="180" x2="610" y2="180" stroke="white" stroke-width="2.5" stroke-opacity="0.85"/>
										<line x1="360" y1="0" x2="360" y2="360" stroke="white" stroke-width="3" stroke-opacity="0.6"/>
										<line x1="360" y1="0" x2="360" y2="360" stroke="#007AFF" stroke-width="1.5" stroke-dasharray="3 3" stroke-opacity="0.4"/>
									</svg>
								</div>
								<div class="absolute inset-0 bg-black/20 pointer-events-none z-0"></div>

								<div class="relative z-10 flex flex-col h-full items-center justify-center">
									<!-- Symmetrical Court Layout -->
									<div class="grid grid-cols-[1fr_48px_1fr] items-center w-full py-8 text-center">
										<!-- Team 1 (Left Half) -->
										<div class="flex flex-col text-center items-center justify-center">
											{#each match.team1 as p}
												<span
													class="text-sm font-black tracking-wide break-words text-white sm:text-base"
													style="text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;"
												>
													{p.name}
												</span>
											{/each}
										</div>

										<!-- Middle net area VS -->
										<div class="flex items-center justify-center">
											<span
												class="px-1 text-[11px] font-black tracking-wider uppercase select-none text-white/65"
												style="text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;"
											>
												VS
											</span>
										</div>

										<!-- Team 2 (Right Half) -->
										<div class="flex flex-col text-center items-center justify-center">
											{#each match.team2 as p}
												<span
													class="text-sm font-black tracking-wide break-words text-white sm:text-base"
													style="text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;"
												>
													{p.name}
												</span>
											{/each}
										</div>
									</div>
								</div>

								{#if match.score1 != null && match.score2 != null && !round.completed}
									<div class="absolute top-4 right-4 z-20 animate-fade-in" in:scale={{ duration: 400 }}>
										<div class="h-1.5 w-1.5 rounded-full bg-accent"></div>
									</div>
								{/if}
							</div>

							<!-- Score Entry Row (Below Card) -->
							<div class="mt-3 flex items-center justify-center gap-2 relative">
								{#if !round.completed}
									<input
										type="text"
										inputmode="numeric"
										pattern="[0-9]*"
										enterkeyhint="done"
										aria-label={`${round.name || `Round ${round.number}`} match ${mIdx + 1} team 1 score`}
										class="h-[52px] w-14 cursor-pointer rounded-lg text-center text-lg font-black transition-all outline-none border border-border/10 bg-[#0d1117] text-foreground focus:border-[#007AFF] focus:bg-[#007AFF]/5"
										placeholder="0"
										value={match.score1 != null ? match.score1 : ''}
										onfocus={(e) => {
											(e.target as HTMLInputElement).select();
											activeScoreSelector = { rIdx: idx, mIdx: mIdx, team: 1 };
										}}
										onclick={() => {
											activeScoreSelector = { rIdx: idx, mIdx: mIdx, team: 1 };
										}}
										oninput={(e) => {
											const el = e.target as HTMLInputElement;
											const val = parseScoreInput(el.value, ts.pointsPerMatch);
											if (val == null && el.value.trim() !== '') {
												el.value = match.score1 != null ? String(match.score1) : '';
												showToast('Scores must be whole numbers', 'error');
												return;
											}
											handleScoreChange(idx, mIdx, 1, val);
										}}
									/>
									<span class="text-foreground/25 font-bold">-</span>
									<input
										type="text"
										inputmode="numeric"
										pattern="[0-9]*"
										enterkeyhint="done"
										aria-label={`${round.name || `Round ${round.number}`} match ${mIdx + 1} team 2 score`}
										class="h-[52px] w-14 cursor-pointer rounded-lg text-center text-lg font-black transition-all outline-none border border-border/10 bg-[#0d1117] text-foreground focus:border-[#007AFF] focus:bg-[#007AFF]/5"
										placeholder="0"
										value={match.score2 != null ? match.score2 : ''}
										onfocus={(e) => {
											(e.target as HTMLInputElement).select();
											activeScoreSelector = { rIdx: idx, mIdx: mIdx, team: 2 };
										}}
										onclick={() => {
											activeScoreSelector = { rIdx: idx, mIdx: mIdx, team: 2 };
										}}
										oninput={(e) => {
											const el = e.target as HTMLInputElement;
											const val = parseScoreInput(el.value, ts.pointsPerMatch);
											if (val == null && el.value.trim() !== '') {
												el.value = match.score2 != null ? String(match.score2) : '';
												showToast('Scores must be whole numbers', 'error');
												return;
											}
											handleScoreChange(idx, mIdx, 2, val);
										}}
									/>

									{#if activeScoreSelector && activeScoreSelector.rIdx === idx && activeScoreSelector.mIdx === mIdx}
										{@const selectedTeam = activeScoreSelector.team}
										<!-- Backdrop to close -->
										<button
											type="button"
											aria-label="Close score picker"
											class="fixed inset-0 z-40 bg-transparent"
											onclick={() => (activeScoreSelector = null)}
										></button>
										<!-- Popover Selector -->
										<div
											class="absolute top-full left-1/2 -translate-x-1/2 mt-2 z-50 bg-[#0d1117] border border-border/20 rounded-xl p-3 shadow-2xl backdrop-blur-md w-[240px]"
										>
											<div class="mb-2 text-center text-[9px] font-black tracking-wider text-foreground/40 uppercase">
												Select Score for Team {selectedTeam}
											</div>
											<div class="grid grid-cols-4 gap-2 max-h-[208px] overflow-y-auto pr-0.5 custom-scrollbar">
												{#each Array.from({ length: (ts.pointsPerMatch || 24) + 1 }, (_, i) => i) as val}
													<button
														type="button"
														class="h-[44px] w-[44px] flex items-center justify-center text-xs font-black rounded-md border border-border/10 bg-foreground/[0.02] text-foreground hover:bg-[#007AFF] hover:border-[#007AFF] hover:text-white transition-all cursor-pointer"
														onclick={() => {
															handleScoreChange(idx, mIdx, selectedTeam, val);
															activeScoreSelector = null;
														}}
													>
														{val}
													</button>
												{/each}
											</div>
										</div>
									{/if}
								{:else}
									<div class="flex items-center gap-3 rounded-lg border border-border/10 bg-foreground/[0.02] px-4 py-2 text-sm font-black select-none">
										<span class={winner === 1 ? 'text-foreground' : 'text-foreground/35'}>
											{match.score1}
										</span>
										<span class="text-foreground/20">-</span>
										<span class={winner === 2 ? 'text-foreground' : 'text-foreground/35'}>
											{match.score2}
										</span>
									</div>
								{/if}
							</div>

							<!-- Complete/Edit Controls -->
							{#if round.completed}
								<div class="mt-2 flex justify-center">
									<button
										type="button"
										class="min-h-[44px] cursor-pointer px-3 text-[9px] font-black tracking-wider uppercase transition-colors text-foreground/40 hover:text-foreground"
										onclick={() => handleEditRound(idx, mIdx)}
									>
										Edit Result
									</button>
								</div>
							{/if}
						</div>
					{:else}
						<div
							class={cn(
								'group relative overflow-hidden border-b border-border/10 pt-5 pb-5 transition-all duration-200 first:pt-1 last:border-0 -mx-4 px-4',
								isSelectedMatch && 'z-10 scale-[1.005] rounded-r-md border-l-2 border-l-accent bg-foreground/[0.02]'
							)}
						>
							<!-- Match Header (Court Info) -->
							<div
								class="mb-2.5 flex items-center justify-between py-1 text-[10px] font-black tracking-wider text-foreground/40 uppercase"
							>
								<div class="flex items-center gap-2">
									{#if matchDivision}
										<span class="text-accent">DIV {matchDivision}</span>
										<span class="text-foreground/15">•</span>
									{/if}
									<span>{getCourtName(match.court, matchDivision)}</span>
								</div>
								<span>
									{ts.scoringMode === 'total'
										? 'Symmetric'
										: ts.scoringMode === 'race'
											? 'Race'
											: 'Timed'}
								</span>
							</div>

							<!-- Scoreboard Grid Row -->
							<div class="grid grid-cols-[1fr_auto_1fr] items-center gap-4 py-2.5">
								<!-- Team 1 (Left) -->
								<div class="flex min-w-0 flex-col text-right">
									{#each match.team1 as p}
										<span class="text-xs font-black tracking-wide break-words text-foreground sm:text-sm">
											{p.name}
										</span>
									{/each}
								</div>

								<!-- Digital Scoreboard Center -->
								<div class="flex items-center gap-2">
									{#if !round.completed}
										<input
											type="text"
											inputmode="numeric"
											pattern="[0-9]*"
											enterkeyhint="done"
											aria-label={`${round.name || `Round ${round.number}`} match ${mIdx + 1} team 1 score`}
											class="h-12 w-12 cursor-pointer rounded-lg border border-white/10 bg-[#0d1117] text-center text-xl font-bold text-foreground transition-all outline-none placeholder:text-foreground/20 focus:border-[#007AFF] focus:bg-[#007AFF]/5"
											placeholder="0"
											value={match.score1 != null ? match.score1 : ''}
											onfocus={(e) => (e.target as HTMLInputElement).select()}
											oninput={(e) => {
												const el = e.target as HTMLInputElement;
												const val = parseScoreInput(el.value, ts.pointsPerMatch);
												if (val == null && el.value.trim() !== '') {
													el.value = match.score1 != null ? String(match.score1) : '';
													showToast('Scores must be whole numbers', 'error');
													return;
												}
												handleScoreChange(idx, mIdx, 1, val);
											}}
										/>
									{:else}
										<span
											class={cn(
												'w-12 text-center text-2xl font-black tabular-nums select-none',
												winner === 1 ? 'text-foreground' : 'text-foreground/20'
											)}
										>
											{match.score1}
										</span>
									{/if}

									<span class="px-1 text-[11px] font-black tracking-wider text-foreground/20 uppercase select-none">VS</span>

									{#if !round.completed}
										<input
											type="text"
											inputmode="numeric"
											pattern="[0-9]*"
											enterkeyhint="done"
											aria-label={`${round.name || `Round ${round.number}`} match ${mIdx + 1} team 2 score`}
											class="h-12 w-12 cursor-pointer rounded-lg border border-white/10 bg-[#0d1117] text-center text-xl font-bold text-foreground transition-all outline-none placeholder:text-foreground/20 focus:border-[#007AFF] focus:bg-[#007AFF]/5"
											placeholder="0"
											value={match.score2 != null ? match.score2 : ''}
											onfocus={(e) => (e.target as HTMLInputElement).select()}
											oninput={(e) => {
												const el = e.target as HTMLInputElement;
												const val = parseScoreInput(el.value, ts.pointsPerMatch);
												if (val == null && el.value.trim() !== '') {
													el.value = match.score2 != null ? String(match.score2) : '';
													showToast('Scores must be whole numbers', 'error');
													return;
												}
												handleScoreChange(idx, mIdx, 2, val);
											}}
										/>
									{:else}
										<span
											class={cn(
												'w-12 text-center text-2xl font-black tabular-nums select-none',
												winner === 2 ? 'text-foreground' : 'text-foreground/20'
											)}
										>
											{match.score2}
										</span>
									{/if}
								</div>

								<!-- Team 2 (Right) -->
								<div class="flex min-w-0 flex-col text-left">
									{#each match.team2 as p}
										<span class="text-xs font-black tracking-wide break-words text-foreground sm:text-sm">
											{p.name}
										</span>
									{/each}
								</div>
							</div>

							<!-- Complete/Edit Controls -->
							{#if round.completed}
								<div class="mt-1 flex justify-center pt-2">
									<button
										type="button"
										class="min-h-[44px] cursor-pointer px-3 text-[9px] font-black tracking-wider text-foreground/40 uppercase transition-colors hover:text-foreground"
										onclick={() => handleEditRound(idx, mIdx)}
									>
										Edit Result
									</button>
								</div>
							{/if}

							{#if match.score1 != null && match.score2 != null && !round.completed}
								<div class="absolute top-4 right-4 z-20 animate-fade-in" in:scale={{ duration: 400 }}>
									<div class="h-1.5 w-1.5 rounded-full bg-accent"></div>
								</div>
							{/if}
						</div>
					{/if}
				{/each}
			</div>

			<!-- Rest Rotation (Manual Byes) & Completion Panel (Only for Active Round) -->
			{#if !round.completed && isActiveRound}
				<div class="space-y-8 border-t border-border/10 pt-8">
					{#if format !== 'division'}
						<div class="space-y-4">
							<div class="flex items-center justify-between">
								<div class="space-y-0.5">
									<h4 class="text-[10px] font-black tracking-wider text-foreground uppercase">
										Rest Rotation
									</h4>
									<p class="text-[8px] tracking-wider text-foreground/35 uppercase">
										Select manually for next round bypass
									</p>
								</div>
								<span class="text-[10px] font-black tracking-wider text-accent uppercase">
									{ts.manualByes.length} SELECTED
								</span>
							</div>

							<div class="flex flex-wrap gap-2">
								{#each ts.leaderboard as p}
									<button
										type="button"
										class={cn(
											'min-h-[48px] cursor-pointer rounded-md border px-4 py-2.5 text-[9px] font-black tracking-wider uppercase transition-all',
											ts.manualByes.includes(p.id)
												? 'border-foreground bg-foreground text-background shadow-sm'
												: 'border-border/10 bg-foreground/[0.02] text-foreground/45 hover:bg-foreground/[0.06] hover:text-foreground'
										)}
										onclick={() => handleToggleBye(p.id)}
									>
										{p.name}
										<span
											class={cn(
												'ml-1.5 text-[8px] font-normal',
												ts.manualByes.includes(p.id) ? 'text-background/55' : 'opacity-45'
											)}>({p.byeCount || 0})</span
										>
									</button>
								{/each}
							</div>
						</div>
					{/if}

					<!-- Complete Button -->
					<button
						type="button"
						class="w-full cursor-pointer rounded-xl border-0 bg-foreground py-4 font-display text-base font-black tracking-wider text-background uppercase shadow-sm shadow-foreground/5 transition-all duration-200 active:scale-[0.99]"
						onclick={() => {
							const errors = validateRoundScores(round, {
								scoringMode: ts.scoringMode,
								pointsPerMatch: ts.pointsPerMatch
							});
							if (errors.length === 0) {
								handleCompleteRound(idx);
							} else {
								showToast(errors[0], 'error');
							}
						}}
					>
						{#if round.name === 'Final'}
							FINISH TOURNAMENT
						{:else if nextRoundPreview?.name === 'Semifinal'}
							GENERATING SEMIS
						{:else if round.name === 'Semifinal' || nextRoundPreview?.name === 'Final'}
							GENERATING FINAL
						{:else}
							FINISH ROUND {round.number}
						{/if}
					</button>
				</div>
			{/if}
		</div>
	{/if}

	<!-- View Full Schedule Matrix Link (Division Only) -->
	{#if format === 'division' && allRounds && allRounds.length > 0}
		<div class="mt-16 text-center">
			<button
				type="button"
				onclick={() => (isFullScheduleOpen = true)}
				class="min-h-[44px] cursor-pointer border-0 border-b border-border/10 bg-transparent px-3 pb-1 text-[10px] font-black tracking-wider text-foreground/40 uppercase transition-all hover:text-foreground"
			>
				View Full Schedule Matrix
			</button>
		</div>
	{/if}

	<FullScheduleModal isOpen={isFullScheduleOpen} onClose={() => (isFullScheduleOpen = false)} />
</div>

<style>
	/* Hide scrollbar for Chrome, Safari and Opera */
	.scrollbar-none::-webkit-scrollbar {
		display: none;
	}
	/* Hide scrollbar for IE, Edge and Firefox */
	.scrollbar-none {
		-ms-overflow-style: none; /* IE and Edge */
		scrollbar-width: none; /* Firefox */
	}
</style>

// src/tournament/ui/components/Schedule.tsx
import React, { useState, useEffect } from "react";
import { GlassCard } from "@/components/ui/GlassCard";
import {
  useTournament,
  Player,
  Round,
  Match,
} from "@/context/TournamentContext";
import { showConfirmModal } from "@/tournament/core/modals";
import { showToast } from "@/shared/utils";
import { launchConfetti } from "@/tournament/confetti";
import {
  formatEstimatedRoundStart,
  getEstimatedRoundStartRelativeLabel,
} from "./scheduleTiming";

const RoundCard: React.FC<{
  round: Round;
  roundIndex: number;
  isLast: boolean;
  onComplete: () => void;
  onEdit: (matchIndex: number) => void;
  onScoreChange: (matchIndex: number, team: 1 | 2, val: number) => void;
  onToggleBye: (playerId: string) => void;
  nextRoundPreview?: Round | null;
}> = ({
  round,
  roundIndex,
  isLast,
  onComplete,
  onEdit,
  onScoreChange,
  onToggleBye,
  nextRoundPreview,
}) => {
  const { state, dispatch } = useTournament();
  const [isCollapsed, setIsCollapsed] = useState(round.completed && !isLast);

  const getDivisionStyles = (division: string) => {
    switch (division.toUpperCase()) {
      case "A": return "bg-pool-a/10 text-pool-a border-pool-a/20";
      case "B": return "bg-pool-b/10 text-pool-b border-pool-b/20";
      case "C": return "bg-pool-c/10 text-pool-c border-pool-c/20";
      case "D": return "bg-pool-d/10 text-pool-d border-pool-d/20";
      default: return "bg-accent/10 text-accent border-accent/20";
    }
  };
  const [elapsed, setElapsed] = useState(0);

  useEffect(() => {
    if (round.completed) return;

    const selectedMatchId = state.ui.selectedMatchId;
    if (!selectedMatchId?.startsWith(`round-${roundIndex}-match-`)) return;

    const matchEl = document.getElementById(selectedMatchId);
    if (!matchEl) return;

    matchEl.scrollIntoView({ behavior: "smooth", block: "center" });
    const firstInput = matchEl.querySelector("input");
    if (firstInput instanceof HTMLInputElement) {
      firstInput.focus();
      firstInput.select();
    }

    dispatch({
      type: "UPDATE_FIELD",
      key: "ui",
      value: { ...state.ui, selectedMatchId: null },
    });
  }, [dispatch, round.completed, roundIndex, state.ui]);

  // Live timer for active round
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (!round.completed && state.roundStartedAt) {
      interval = setInterval(() => {
        setElapsed(Math.floor((Date.now() - state.roundStartedAt!) / 1000));
      }, 1000);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [round.completed, state.roundStartedAt]);

  const formatDuration = (secs: number) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m}:${s.toString().padStart(2, "0")}`;
  };

  const getCourtName = (courtNum: number) => {
    if (
      state.courtFormat === "custom" &&
      state.customCourtNames[courtNum - 1]
    ) {
      return state.customCourtNames[courtNum - 1];
    }
    return `Court ${courtNum}`;
  };

  const getConstraintLabel = (constraint?: string) => {
    if (constraint === "repeats") return "Repeat allowed (Priority: Pattern)";
    if (constraint === "pattern") return "Pattern override (Priority: Repeats)";
    return "Constraint relaxed (Best effort)";
  };

  const getRoundCompletionStatus = () => {
    let completedCount = 0;
    const missing: string[] = [];

    round.matches.forEach((m) => {
      const hasScores =
        m.score1 !== undefined &&
        m.score1 !== null &&
        m.score2 !== undefined &&
        m.score2 !== null;
      if (hasScores) {
        completedCount++;
      } else {
        missing.push(getCourtName(m.court));
      }
    });

    if (completedCount === 0) return { status: "empty", missing };
    if (completedCount === round.matches.length)
      return { status: "complete", missing: [] };
    return { status: "partial", missing };
  };

  const { status, missing } = getRoundCompletionStatus();

  const handleCompleteClick = () => {
    if (status === "complete") {
      onComplete();
    } else if (status === "partial") {
      const msg = `Missing scores for:\n${missing
        .map((c) => "• " + c)
        .join("\n")}\n\nContinue anyway?`;
      showConfirmModal("Incomplete Round", msg, "Continue Anyway", onComplete);
    } else {
      showConfirmModal(
        "No Scores Entered",
        "You haven't entered any scores for this round. Are you sure you want to complete it as all 0-0?",
        "Complete w/ Zeros",
        onComplete,
      );
    }
  };

  const getCompleteButtonLabel = () => {
    if (round.name === "Final") return "Finish Tournament";
    if (nextRoundPreview?.name === "Semifinal") {
      return `Complete Round ${round.number} & Generate Semis`;
    }
    if (round.name === "Semifinal" || nextRoundPreview?.name === "Final") {
      return "Complete Semifinal & Generate Final";
    }
    return `Complete Round ${round.number}`;
  };

  return (
    <GlassCard
      padding="none"
      className={`overflow-hidden mb-6 transition-all scroll-mt-24 ${
        round.completed ? "opacity-80" : ""
      }`}
      id={`round-${roundIndex}`}
    >
      {/* Round Header */}
      <div
        className={`flex items-center justify-between px-4 py-3 border-b border-border cursor-pointer ${
          round.completed ? "bg-popover/50" : "bg-accent/5"
        }`}
        onClick={() => round.completed && setIsCollapsed(!isCollapsed)}
      >
        <div className="flex items-center gap-3">
          <span className="text-lg font-bold text-foreground">
            {round.name || `Round ${round.number}`}
          </span>
          {!round.completed && !state.roundStartedAt ? (
            /* Timer not started yet — show Start button */
            <button
              className="flex items-center gap-1.5 px-3 py-1 text-sm font-semibold bg-success hover:bg-success/80 text-white rounded-lg transition-colors"
              onClick={(e) => {
                e.stopPropagation();
                dispatch({ type: "UPDATE_FIELD", key: "roundStartedAt", value: Date.now() });
              }}
            >
              ▶ Start
            </button>
          ) : (
            <span className="text-sm font-mono bg-black/20 px-2 py-0.5 rounded border border-white/5 text-muted-foreground">
              {round.completed 
                ? formatDuration(round.durationSeconds || 0) 
                : formatDuration(elapsed)}
            </span>
          )}
          {round.completed ? (
            <span className="px-2 py-0.5 text-xs font-medium bg-success/20 text-success rounded-full">
              ✓ Completed
            </span>
          ) : state.roundStartedAt ? (
            <span className="px-2 py-0.5 text-xs font-medium bg-accent/20 text-accent rounded-full animate-pulse">
              ● Ongoing
            </span>
          ) : (
            <span className="px-2 py-0.5 text-xs font-medium bg-warning/20 text-warning rounded-full">
              ⏸ Ready
            </span>
          )}
        </div>
        {round.completed && isCollapsed && (
          <span className="text-sm text-muted-foreground">
            {round.matches.map((m) => `${m.score1}-${m.score2}`).join(" · ")}
          </span>
        )}
        {round.completed && (
          <span className="text-muted-foreground text-sm">
            {isCollapsed ? "▶" : "▼"}
          </span>
        )}
      </div>

      {/* Round Content */}
      {!isCollapsed && (
        <div className="p-4">
          {/* Matches Grid */}
          <div
            className="grid gap-4"
            style={{
              gridTemplateColumns:
                state.gridColumns > 0
                  ? `repeat(${state.gridColumns}, minmax(0, 1fr))`
                  : "repeat(auto-fit, minmax(280px, 1fr))",
              fontSize: `${state.textSize}%`,
            }}
          >
            {round.matches.map((match, mIdx) => {
              const matchCardId = `round-${roundIndex}-match-${mIdx}`;
              const isSelectedMatch = state.ui.selectedMatchId === matchCardId;
              // Determine division from players in this match
              const matchDivision = state.format === "division"
                ? (match.team1[0] as any)?.division || "A"
                : null;
              const divColors: Record<string, { border: string; badge: string; glow: string }> = {
                A: { border: "border-blue-500/50", badge: "bg-blue-500", glow: "shadow-blue-500/20" },
                B: { border: "border-emerald-500/50", badge: "bg-emerald-500", glow: "shadow-emerald-500/20" },
                C: { border: "border-orange-500/50", badge: "bg-orange-500", glow: "shadow-orange-500/20" },
              };
              const divStyle = matchDivision ? divColors[matchDivision] || divColors.A : null;

              return (
              <div
                id={matchCardId}
                key={mIdx}
                className={`bg-popover rounded-xl border overflow-hidden relative group ${
                  isSelectedMatch
                    ? "border-accent ring-2 ring-accent/40 shadow-lg shadow-accent/20"
                    : divStyle
                      ? `${divStyle.border} shadow-lg ${divStyle.glow}`
                      : "border-border"
                }`}
              >
                {/* Court Background */}
                <div 
                  className="absolute inset-0 opacity-100 pointer-events-none bg-center bg-no-repeat bg-cover z-0"
                  style={{ backgroundImage: "url('/assets/court-bg.svg')" }}
                />
                
                <div className="relative z-10 flex flex-col h-full">
                  {/* Match Header */}
                  <div className="flex items-center justify-between px-3 py-2 bg-black/40 backdrop-blur-sm border-b border-white/10">
                    <div className="flex items-center gap-2">
                      {matchDivision && divStyle && (
                        <span className={`px-1.5 py-0.5 text-[10px] font-black rounded ${divStyle.badge} text-white uppercase tracking-wider`}>
                          {matchDivision}
                        </span>
                      )}
                      <span className="text-sm font-bold text-white drop-shadow-md">
                        {getCourtName(match.court)}
                      </span>
                    </div>
                    <span className="text-xs text-white/80 font-medium">
                      {state.scoringMode === "total"
                        ? `Total ${state.pointsPerMatch}`
                        : state.scoringMode === "race"
                          ? `Race to ${state.pointsPerMatch}`
                          : `${state.pointsPerMatch} mins`}
                    </span>
                    {match.relaxedConstraint && (
                      <span
                        className="w-5 h-5 flex items-center justify-center text-xs bg-warning/40 text-white border border-white/20 rounded-full cursor-help"
                        title={getConstraintLabel(match.relaxedConstraint)}
                      >
                        i
                      </span>
                    )}
                  </div>

                  {/* Teams */}
                  <div className="p-4 flex-1 flex flex-col justify-between">
                    <div className="flex justify-between items-center mb-4 relative">
                      {/* Team 1 */}
                      <div className="flex-1 text-center">
                        {match.team1.map((p) => {
                          const names = p.name.includes("/") ? p.name.split("/") : [p.name];
                          return names.map((name, ni) => (
                            <div
                              key={`${p.id}-${ni}`}
                              className="font-bold drop-shadow-md truncate text-white"
                            >
                              {name.trim()}
                            </div>
                          ));
                        })}
                      </div>

                      <div className="text-white/60 font-black px-3 text-sm italic shrink-0">
                        VS
                      </div>

                      {/* Team 2 */}
                      <div className="flex-1 text-center">
                        {match.team2.map((p) => {
                          const names = p.name.includes("/") ? p.name.split("/") : [p.name];
                          return names.map((name, ni) => (
                            <div
                              key={`${p.id}-${ni}`}
                              className="font-bold drop-shadow-md truncate text-white"
                            >
                              {name.trim()}
                            </div>
                          ));
                        })}
                      </div>
                    </div>

                    {/* Score Input/Display */}
                    <div className="flex items-center justify-center gap-3">
                      {!round.completed ? (
                        <>
                          <input
                            type="text"
                            inputMode="numeric"
                            pattern="[0-9]*"
                            className={`w-16 h-12 text-center text-2xl font-black bg-black/50 border border-white/20 rounded-lg placeholder:text-white/30 focus:outline-none focus:border-white focus:ring-1 focus:ring-white transition-all shadow-inner [appearance:textfield] ${
                              (match.score1 ?? 0) > (match.score2 ?? 0) ? "text-green-400" : (match.score1 ?? 0) < (match.score2 ?? 0) ? "text-red-400" : (match.score1 !== 0 || match.score2 !== 0) ? "text-orange-400" : "text-white"
                            }`}
                            placeholder="0"
                            value={match.score1 != null && match.score1 !== 0 ? match.score1 : ""}
                            onFocus={(e) => e.target.select()}
                            onChange={(e) => {
                              const val = e.target.value === "" ? 0 : parseInt(e.target.value);
                              if (!isNaN(val)) onScoreChange(mIdx, 1, val);
                            }}
                          />
                          <span className="text-2xl text-white/50 font-black">
                            -
                          </span>
                          <input
                            type="text"
                            inputMode="numeric"
                            pattern="[0-9]*"
                            className={`w-16 h-12 text-center text-2xl font-black bg-black/50 border border-white/20 rounded-lg placeholder:text-white/30 focus:outline-none focus:border-white focus:ring-1 focus:ring-white transition-all shadow-inner [appearance:textfield] ${
                              (match.score2 ?? 0) > (match.score1 ?? 0) ? "text-green-400" : (match.score2 ?? 0) < (match.score1 ?? 0) ? "text-red-400" : (match.score2 !== 0 || match.score1 !== 0) ? "text-orange-400" : "text-white"
                            }`}
                            placeholder="0"
                            value={match.score2 != null && match.score2 !== 0 ? match.score2 : ""}
                            onFocus={(e) => e.target.select()}
                            onChange={(e) => {
                              const val = e.target.value === "" ? 0 : parseInt(e.target.value);
                              if (!isNaN(val)) onScoreChange(mIdx, 2, val);
                            }}
                          />
                        </>
                      ) : (
                        <div className="flex flex-col items-center gap-2 w-full">
                          <div className="flex items-center gap-4">
                            <span className={`text-4xl font-black drop-shadow-xl ${
                              (match.score1 ?? 0) > (match.score2 ?? 0) ? "text-green-400" : (match.score1 ?? 0) < (match.score2 ?? 0) ? "text-red-400" : "text-orange-400"
                            }`}>
                              {match.score1}
                            </span>
                            <span className="text-2xl text-white/40 font-black">-</span>
                            <span className={`text-4xl font-black drop-shadow-xl ${
                              (match.score2 ?? 0) > (match.score1 ?? 0) ? "text-green-400" : (match.score2 ?? 0) < (match.score1 ?? 0) ? "text-red-400" : "text-orange-400"
                            }`}>
                              {match.score2}
                            </span>
                          </div>
                          <button
                            className="px-3 py-1 text-[10px] font-black uppercase tracking-widest text-white/40 hover:text-white bg-white/5 hover:bg-white/10 rounded-full border border-white/5 transition-all"
                            onClick={() => onEdit(mIdx)}
                          >
                            Edit Result
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
                {/* Completed Checkmark Overlay */}
                {(match.score1 != null && match.score2 != null) && !round.completed && (
                  <div className="absolute top-2 right-2 z-20 w-5 h-5 bg-success rounded-full flex items-center justify-center shadow-lg border border-white/20 animate-in zoom-in duration-300">
                    <span className="text-[10px] text-white font-bold">✓</span>
                  </div>
                )}
              </div>
              );
            })}
          </div>

          {/* Byes */}
          {round.byes && round.byes.length > 0 && (
            <div className="mt-4 px-4 py-2 bg-warning/10 rounded-lg border border-warning/20 text-center">
              <span className="text-xs font-semibold text-warning uppercase mr-2">
                Resting:
              </span>
              <span className="text-sm text-muted-foreground">
                {round.byes.map((p) => p.name).join(", ")}
              </span>
            </div>
          )}

          {nextRoundPreview && nextRoundPreview.matches.length > 0 && (
            <div className="mt-6 rounded-2xl border border-accent/20 bg-accent/5 p-4">
              <div className="flex items-center justify-between gap-3 mb-4">
                <div>
                  <h4 className="text-xs font-black uppercase tracking-[0.2em] text-accent">
                    Nästa Runda (Förhandsvisning)
                  </h4>
                  <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-1">
                    <p className="text-sm text-muted-foreground">
                      Lag som väntar på Runda {nextRoundPreview.number}.
                    </p>
                    <span className="text-sm font-bold text-foreground">
                      Est. start: {formatEstimatedRoundStart(state, nextRoundPreview.number - 1)}
                    </span>
                    <span className="px-2 py-0.5 rounded-full bg-background/70 border border-accent/15 text-[10px] font-black uppercase tracking-wider text-accent">
                      {getEstimatedRoundStartRelativeLabel(state, nextRoundPreview.number - 1)}
                    </span>
                  </div>
                </div>
                <span className="px-3 py-1 rounded-full bg-accent text-white text-[10px] font-black uppercase tracking-wider">
                  Runda {nextRoundPreview.number}
                </span>
              </div>

              <div className="grid gap-3 md:grid-cols-2">
                {nextRoundPreview.matches.map((match, idx) => {
                  const matchDivision =
                    state.format === "division"
                      ? (match.team1[0] as any)?.division || "A"
                      : null;

                  return (
                  <div
                    key={`${nextRoundPreview.number}-${idx}`}
                    className="rounded-2xl border border-border bg-card/80 px-4 py-3"
                  >
                    <div className="flex items-center justify-between gap-2 mb-2">
                      <div className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                        {getCourtName(match.court)}
                      </div>
                      {matchDivision && (
                        <span className={`px-2 py-0.5 rounded-full border text-[9px] font-black uppercase tracking-wider ${getDivisionStyles(matchDivision)}`}>
                          Division {matchDivision}
                        </span>
                      )}
                    </div>
                    <div className="flex items-center justify-between gap-3 text-sm">
                      <div className="flex-1 font-semibold text-foreground truncate">
                        {match.team1.map((player) => player.name).join(" / ")}
                      </div>
                      <div className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/40">
                        vs
                      </div>
                      <div className="flex-1 text-right font-semibold text-foreground truncate">
                        {match.team2.map((player) => player.name).join(" / ")}
                      </div>
                    </div>
                  </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Bye Selector & Complete Button */}
          {!round.completed && isLast && (
            <div className="mt-6 space-y-4">
              {/* Bye Selector - Hidden in division format since schedule is predetermined */}
              {state.format !== "division" && (
                <div className="bg-popover rounded-xl p-4 border border-border">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-sm font-medium text-muted-foreground">
                      Toggle who rests next round:
                    </span>
                    <span className="text-xs text-muted-foreground">
                      ({state.manualByes.length} selected)
                    </span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {state.leaderboard.map((p) => (
                      <button
                        key={p.id}
                        className={`px-3 py-1.5 text-sm rounded-lg border transition-colors ${
                          state.manualByes.includes(p.id)
                            ? "bg-warning/20 border-warning text-warning"
                            : "bg-card border-border text-muted-foreground hover:text-foreground"
                        }`}
                        onClick={() => onToggleBye(p.id)}
                      >
                        {p.name}
                        <span className="text-xs ml-1 opacity-60">
                          ({p.byeCount || 0})
                        </span>
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Complete Button */}
              <button
                className={`w-full py-3 font-black uppercase tracking-widest rounded-xl transition-all shadow-lg active:scale-95 ${
                  status === "complete"
                    ? "bg-success hover:bg-success/80 text-white shadow-success/20"
                    : "bg-popover hover:bg-card border border-border text-muted-foreground"
                }`}
                onClick={handleCompleteClick}
              >
                {getCompleteButtonLabel()}
              </button>
            </div>
          )}
        </div>
      )}
    </GlassCard>
  );
};

import FullScheduleModal from "./FullScheduleModal";

const Schedule: React.FC = () => {
  const { state, dispatch } = useTournament();
  const { schedule } = state;

  // Auto-scroll to the new round when schedule length increases
  useEffect(() => {
    if (schedule.length > 0) {
      const lastRoundIdx = schedule.length - 1;
      const el = document.getElementById(`round-${lastRoundIdx}`);
      if (el) {
        // Small delay to ensure render is complete and layout is settled
        setTimeout(() => {
          el.scrollIntoView({ behavior: "smooth", block: "start" });
        }, 100);
      }
    }
  }, [schedule.length]);

  const getCourtName = (courtNum: number) => {
    if (
      state.courtFormat === "custom" &&
      state.customCourtNames[courtNum - 1]
    ) {
      return state.customCourtNames[courtNum - 1];
    }
    return `Court ${courtNum}`;
  };

  const nextRoundPreview =
    state.format === "division" &&
    state.allRounds &&
    schedule.length < state.allRounds.length
      ? state.allRounds[schedule.length]
      : null;

  const [isFullScheduleOpen, setIsFullScheduleOpen] = useState(false);

  const handleScoreChange = (
    rIdx: number,
    mIdx: number,
    team: 1 | 2,
    val: number,
  ) => {
    const newSchedule = [...schedule];
    const match = { ...newSchedule[rIdx].matches[mIdx] };
    if (team === 1) match.score1 = val;
    else match.score2 = val;

    if (state.scoringMode === "total") {
      if (team === 1) match.score2 = state.pointsPerMatch - val;
      else match.score1 = state.pointsPerMatch - val;
    } else if (state.scoringMode === "race") {
      // If entered score is less than target, other team must have won (reached target)
      // If entered score IS target, other team can be anything < target (we don't auto-fill)
      if (val < state.pointsPerMatch) {
        if (team === 1) match.score2 = state.pointsPerMatch;
        else match.score1 = state.pointsPerMatch;
      }
    }

    newSchedule[rIdx].matches[mIdx] = match;
    dispatch({ type: "UPDATE_FIELD", key: "schedule", value: newSchedule });
  };

  const handleCompleteRound = (rIdx: number) => {
    if (schedule[rIdx]?.name === "Final") {
      launchConfetti();
    }
    dispatch({ type: "COMPLETE_ROUND" });
    showToast(`Round ${rIdx + 1} Completed!`, "success");
  };

  const handleEditRound = (rIdx: number, mIdx: number) => {
    dispatch({ type: "EDIT_ROUND", roundIndex: rIdx, matchIndex: mIdx });
    showToast(`Round ${rIdx + 1} re-opened. Match ${mIdx + 1} is ready to edit`, "info");
  };

  const handleToggleBye = (playerId: string) => {
    const newByes = state.manualByes.includes(playerId)
      ? state.manualByes.filter((id) => id !== playerId)
      : [...state.manualByes, playerId];
    dispatch({ type: "UPDATE_FIELD", key: "manualByes", value: newByes });
  };

  const getRoundMetaLabel = (round: Round, idx: number) => {
    if (!round.completed) {
      return `Est. Start: ${formatEstimatedRoundStart(state, idx)}`;
    }

    if (round.durationSeconds == null) {
      return "Finished";
    }

    return `Finished · ${Math.round(round.durationSeconds / 60)} min`;
  };

  return (
    <div>
      {schedule.map((round, idx) => (
        <div key={idx} id={`round-${idx}`} className="relative">
          <div className="absolute -top-4 left-6 z-10">
            <span className="px-3 py-1 rounded-full bg-background border border-border text-[10px] font-black uppercase tracking-widest text-muted-foreground shadow-sm">
              {getRoundMetaLabel(round, idx)}
            </span>
          </div>
          <RoundCard
            round={round}
            roundIndex={idx}
            isLast={idx === schedule.length - 1}
            onComplete={() => handleCompleteRound(idx)}
            onEdit={(matchIndex) => handleEditRound(idx, matchIndex)}
            onScoreChange={(mIdx, team, val) =>
              handleScoreChange(idx, mIdx, team, val)
            }
            onToggleBye={handleToggleBye}
            nextRoundPreview={idx === schedule.length - 1 ? nextRoundPreview : null}
          />
        </div>
      ))}

      {/* Full Schedule Access Button */}
      {state.format === "division" && state.allRounds && state.allRounds.length > 0 && (
        <div className="mt-8 text-center pb-8">
          <button
            onClick={() => setIsFullScheduleOpen(true)}
            className="inline-flex items-center px-6 py-3 rounded-xl bg-popover hover:bg-card border border-border text-foreground hover:text-accent font-bold transition-all shadow-lg"
          >
            Visa hela spelschemat
          </button>
        </div>
      )}

      <FullScheduleModal
        isOpen={isFullScheduleOpen}
        onClose={() => setIsFullScheduleOpen(false)}
      />
    </div>
  );
};

export default Schedule;
export { RoundCard };
