// src/tournament/ui/components/MatchTimer.tsx
import React, { useEffect, useRef, useState } from "react";
import { useTournament } from "@/context/TournamentContext";
import { showToast } from "@/shared/utils";
import { showConfirmModal } from "../../core/modals";

/**
 * Compact Round Clock for the Toolbar
 * Handles Countdown (Timed mode) or Count-up (Standard mode)
 */
export const MatchTimer: React.FC = () => {
  const { state, dispatch } = useTournament();
  const { timer, scoringMode, roundStartedAt, sessionStartedAt } = state;
  const isTimed = scoringMode === "time";
  
  // Local display state for smooth ticking
  const [roundSeconds, setRoundSeconds] = useState(0);
  const [totalSeconds, setTotalSeconds] = useState(0);
  const intervalRef = useRef<NodeJS.Timeout | null>(null);
  const audioContextRef = useRef<AudioContext | null>(null);

  // Sync with global state
  useEffect(() => {
    if (isTimed) {
      setRoundSeconds(timer.remainingSeconds);
    } else if (roundStartedAt) {
      setRoundSeconds(Math.floor((Date.now() - roundStartedAt) / 1000));
    }
    
    if (sessionStartedAt) {
      setTotalSeconds(Math.floor((Date.now() - sessionStartedAt) / 1000));
    }
  }, [timer.remainingSeconds, roundStartedAt, sessionStartedAt, isTimed]);

  // Tick logic
  useEffect(() => {
    if (timer.isRunning && timer.status !== "completed") {
      intervalRef.current = setInterval(() => {
        // Round Timer
        if (isTimed) {
          setRoundSeconds((prev) => {
            if (prev <= 1) {
              handleComplete();
              return 0;
            }
            if (prev <= 4) playBeep(440, 0.2);
            return prev - 1;
          });
        } else {
          setRoundSeconds((prev) => prev + 1);
        }

        // Total Timer
        setTotalSeconds((prev) => prev + 1);
      }, 1000);
    } else {
      if (intervalRef.current) clearInterval(intervalRef.current);
    }

    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [timer.isRunning, timer.status, isTimed]);

  const handleComplete = () => {
    dispatch({
      type: "UPDATE_TIMER",
      payload: { isRunning: false, status: "completed", remainingSeconds: 0 },
    });
    playBeep(880, 1.0);
    showToast("TIME UP!", "info");
    document.body.classList.add("timer-finished-flash");
    setTimeout(() => document.body.classList.remove("timer-finished-flash"), 1000);
  };

  const toggleStart = () => {
    const newRunning = !timer.isRunning;
    dispatch({
      type: "UPDATE_TIMER",
      payload: {
        isRunning: newRunning,
        status: newRunning ? "running" : "paused",
      },
    });
    if (newRunning) playBeep(880, 0.1);
  };

  const resetRound = () => {
    showConfirmModal(
      "Reset Round Timer?",
      "This will set the round clock back to zero (or the starting duration). Continue?",
      "Reset Clock",
      () => {
        if (isTimed) {
          const seconds = timer.duration * 60;
          dispatch({
            type: "UPDATE_TIMER",
            payload: { isRunning: false, status: "idle", remainingSeconds: seconds },
          });
        } else {
          dispatch({ type: "UPDATE_FIELD", key: "roundStartedAt", value: Date.now() });
        }
        showToast("Round timer reset");
      }
    );
  };

  const formatTime = (secs: number) => {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = Math.floor(secs % 60);
    const timeStr = `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
    return h > 0 ? `${h}:${timeStr}` : timeStr;
  };

  const playBeep = (freq: number, dur: number) => {
    try {
      if (!audioContextRef.current) {
        audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
      }
      const ctx = audioContextRef.current;
      if (ctx.state === "suspended") ctx.resume();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.type = "sine";
      osc.frequency.value = freq;
      osc.connect(gain);
      gain.connect(ctx.destination);
      osc.start();
      gain.gain.setValueAtTime(0.1, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + dur);
      osc.stop(ctx.currentTime + dur);
    } catch (e) {}
  };

  const isCompleted = timer.status === "completed";
  const isLow = isTimed && roundSeconds <= 60;

  return (
    <div className="flex items-center gap-2">
      {/* Round Timer Pill */}
      <div
        className={`flex items-center gap-2 px-3 py-1.5 rounded-full border transition-all duration-300 ${
          isCompleted
            ? "bg-error/20 border-error/50 text-error"
            : timer.isRunning
            ? "bg-accent/10 border-accent/40 text-accent shadow-sm"
            : "bg-black/20 border-white/10 text-muted-foreground"
        }`}
      >
        <button
          onClick={toggleStart}
          className="w-5 h-5 flex items-center justify-center hover:scale-110 transition-transform"
          title={timer.isRunning ? "Pause" : "Start"}
        >
          {timer.isRunning ? "⏸" : "▶"}
        </button>

        <div className="flex flex-col items-center">
          <span className="text-[8px] font-black uppercase tracking-tighter leading-none opacity-60">
            {isTimed ? "Round" : "Round"}
          </span>
          <span 
            className={`font-mono text-sm font-black tracking-tight leading-tight ${
              isLow ? "animate-pulse text-warning" : ""
            }`}
            onClick={resetRound}
            style={{ cursor: 'pointer' }}
            title="Reset Round Clock"
          >
            {formatTime(roundSeconds)}
          </span>
        </div>
      </div>

      {/* Total Timer Pill */}
      <div className="flex items-center gap-2 px-3 py-1.5 rounded-full border border-white/5 bg-black/20 text-muted-foreground/60 min-w-[70px]">
        <div className="flex flex-col items-center w-full">
          <span className="text-[8px] font-black uppercase tracking-tighter leading-none opacity-40">
            Total
          </span>
          <span className="font-mono text-sm font-bold tracking-tight leading-tight">
            {formatTime(totalSeconds)}
          </span>
        </div>
      </div>
    </div>
  );
};

// padelcompanion-svelte/src/lib/components/tournament/MatchTimer.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { tournament } from "$lib/stores/tournament.svelte";
  import { showToast } from "$lib/shared/utils";
  import { showConfirmModal } from "$lib/tournament/core/modals";

  let timer = $derived(tournament.state.timer);
  let scoringMode = $derived(tournament.state.scoringMode);
  let roundStartedAt = $derived(tournament.state.roundStartedAt);
  let sessionStartedAt = $derived(tournament.state.sessionStartedAt);
  let isTimed = $derived(scoringMode === "time");

  let roundSeconds = $state(0);
  let totalSeconds = $state(0);
  let intervalId: any = null;
  let audioCtx: AudioContext | null = null;

  $effect(() => {
    if (isTimed) {
      roundSeconds = timer.remainingSeconds;
    } else if (roundStartedAt) {
      roundSeconds = Math.floor((Date.now() - roundStartedAt) / 1000);
    }

    if (sessionStartedAt) {
      totalSeconds = Math.floor((Date.now() - sessionStartedAt) / 1000);
    }
  });

  $effect(() => {
    if (timer.isRunning && timer.status !== "completed") {
      if (!intervalId) {
        intervalId = setInterval(() => {
          if (isTimed) {
            if (roundSeconds <= 1) {
              handleComplete();
              roundSeconds = 0;
            } else {
              if (roundSeconds <= 4) playBeep(440, 0.2);
              roundSeconds -= 1;
              tournament.updateTimer({ remainingSeconds: roundSeconds });
            }
          } else {
            roundSeconds += 1;
          }
          totalSeconds += 1;
        }, 1000);
      }
    } else {
      if (intervalId) {
        clearInterval(intervalId);
        intervalId = null;
      }
    }
  });

  onDestroy(() => {
    if (intervalId) clearInterval(intervalId);
  });

  function handleComplete() {
    tournament.updateTimer({ isRunning: false, status: "completed", remainingSeconds: 0 });
    playBeep(880, 1.0);
    showToast("TIME UP!", "info");
    document.body.classList.add("timer-finished-flash");
    setTimeout(() => document.body.classList.remove("timer-finished-flash"), 1000);
  }

  function toggleStart() {
    const newRunning = !timer.isRunning;
    tournament.updateTimer({
      isRunning: newRunning,
      status: newRunning ? "running" : "paused",
    });
    if (newRunning) playBeep(880, 0.1);
  }

  function resetRound() {
    showConfirmModal(
      "Reset Round Timer?",
      "This will set the round clock back to zero (or the starting duration). Continue?",
      "Reset Clock",
      () => {
        if (isTimed) {
          const seconds = timer.duration * 60;
          tournament.updateTimer({ isRunning: false, status: "idle", remainingSeconds: seconds });
        } else {
          tournament.updateField("roundStartedAt", Date.now());
        }
        showToast("Round timer reset", "success");
      }
    );
  }

  function formatTime(secs: number) {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = Math.floor(secs % 60);
    const timeStr = `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
    return h > 0 ? `${h}:${timeStr}` : timeStr;
  }

  function playBeep(freq: number, dur: number) {
    try {
      if (!audioCtx) {
        audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
      }
      if (audioCtx.state === "suspended") audioCtx.resume();
      const osc = audioCtx.createOscillator();
      const gain = audioCtx.createGain();
      osc.type = "sine";
      osc.frequency.value = freq;
      osc.connect(gain);
      gain.connect(audioCtx.destination);
      osc.start();
      gain.gain.setValueAtTime(0.1, audioCtx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + dur);
      osc.stop(audioCtx.currentTime + dur);
    } catch (e) {}
  }

  let isCompleted = $derived(timer.status === "completed");
  let isLow = $derived(isTimed && roundSeconds <= 60);
</script>

<div class="flex items-center gap-2 select-none font-sans">
  <!-- Round Timer Pill -->
  <div
    class="flex items-center gap-2 px-3 py-1 rounded-full border transition-all duration-300 {
      isCompleted
        ? 'bg-red-500/10 border-red-500/30 text-red-500'
        : timer.isRunning
          ? 'bg-accent/10 border-accent/30 text-accent shadow-sm'
          : 'bg-white/[0.04] border-white/5 text-muted-foreground'
    }"
  >
    <button
      type="button"
      onclick={toggleStart}
      class="w-5 h-5 flex items-center justify-center hover:scale-115 transition-transform text-xs"
      title={timer.isRunning ? "Pause" : "Start"}
    >
      {timer.isRunning ? "⏸" : "▶"}
    </button>

    <div class="flex flex-col items-center">
      <span class="text-[7px] font-black uppercase tracking-wider leading-none opacity-50">
        Round
      </span>
      <button
        type="button"
        class="font-mono text-[13px] font-black tracking-tight leading-tight {
          isLow ? 'animate-pulse text-warning font-black' : 'text-white'
        }"
        onclick={resetRound}
        title="Reset Round Clock"
      >
        {formatTime(roundSeconds)}
      </button>
    </div>
  </div>

  <!-- Total Timer Pill -->
  <div class="flex items-center gap-2 px-3 py-1 rounded-full border border-white/5 bg-white/[0.04] text-muted-foreground/60 min-w-[70px]">
    <div class="flex flex-col items-center w-full">
      <span class="text-[7px] font-black uppercase tracking-wider leading-none opacity-45">
        Total
      </span>
      <span class="font-mono text-[13px] font-bold tracking-tight leading-tight text-muted-foreground">
        {formatTime(totalSeconds)}
      </span>
    </div>
  </div>
</div>
