// src/components/tournament/TournamentIdentity.tsx
import React, { useState, useEffect } from "react";

interface TournamentIdentityProps {
  format: string;
  initialName: string;
  initialNotes: string;
  onUpdate: (key: "name" | "notes", value: string) => void;
  className?: string;
}

export const TournamentIdentity: React.FC<TournamentIdentityProps> = ({
  format,
  initialName,
  initialNotes,
  onUpdate,
  className = "",
}) => {
  const [localName, setLocalName] = useState(initialName || "");
  const [localNotes, setLocalNotes] = useState(initialNotes || "");

  // Sync with global state if it changes from outside
  useEffect(() => {
    setLocalName(initialName || "");
  }, [initialName]);

  useEffect(() => {
    setLocalNotes(initialNotes || "");
  }, [initialNotes]);

  const handleBlur = (key: "name" | "notes", value: string) => {
    onUpdate(key, value.trim());
  };

  const handleKeyDown = (
    e: React.KeyboardEvent<HTMLInputElement>,
    key: "name" | "notes",
    value: string,
  ) => {
    if (e.key === "Enter") {
      e.currentTarget.blur();
    }
  };

  return (
    <div className={`max-w-xl mx-auto mb-10 text-center ${className}`}>
      <input
        type="text"
        placeholder="Unnamed Tournament"
        className="w-full text-center text-4xl font-extrabold text-foreground bg-transparent border-none focus:outline-none focus:ring-0 placeholder:text-muted-foreground/30 mb-2 truncate"
        value={localName}
        onChange={(e) => setLocalName(e.target.value)}
        onBlur={() => handleBlur("name", localName)}
        onKeyDown={(e) => handleKeyDown(e, "name", localName)}
      />
      <input
        type="text"
        placeholder="Add a short description or location..."
        className="w-full text-center text-sm text-muted-foreground bg-transparent border-none focus:outline-none focus:ring-0 placeholder:text-muted-foreground/30 italic"
        value={localNotes}
        onChange={(e) => setLocalNotes(e.target.value)}
        onBlur={() => handleBlur("notes", localNotes)}
        onKeyDown={(e) => handleKeyDown(e, "notes", localNotes)}
      />
    </div>
  );
};

// padelcompanion-svelte/src/lib/components/tournament/TournamentIdentity.svelte
<script lang="ts">
  import { onMount } from "svelte";

  interface Props {
    format: string;
    initialName: string;
    initialNotes: string;
    onUpdate: (key: "name" | "notes", value: string) => void;
    className?: string;
  }

  let {
    format,
    initialName,
    initialNotes,
    onUpdate,
    className = ""
  }: Props = $props();

  let localName = $state(initialName || "");
  let localNotes = $state(initialNotes || "");

  $effect(() => {
    localName = initialName || "";
  });

  $effect(() => {
    localNotes = initialNotes || "";
  });

  function handleBlur(key: "name" | "notes", value: string) {
    onUpdate(key, value.trim());
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter") {
      (e.target as HTMLElement).blur();
    }
  }
</script>

<div class="max-w-xl mx-auto mb-10 text-center {className} relative z-15 select-none">
  <input
    type="text"
    placeholder="Unnamed Tournament"
    class="w-full text-center text-4xl font-black text-white bg-transparent border-none focus:outline-none focus:ring-0 placeholder:text-muted-foreground/30 mb-2 truncate font-display tracking-tight"
    bind:value={localName}
    onblur={() => handleBlur("name", localName)}
    onkeydown={handleKeyDown}
  />
  <input
    type="text"
    placeholder="Add a short description or location..."
    class="w-full text-center text-sm text-muted-foreground bg-transparent border-none focus:outline-none focus:ring-0 placeholder:text-muted-foreground/30 italic font-sans"
    bind:value={localNotes}
    onblur={() => handleBlur("notes", localNotes)}
    onkeydown={handleKeyDown}
  />
</div>
