// src/lib/components/Header.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { cn } from '$lib/shared/utils';
	import { initTheme, toggleTheme } from '$lib/shared/theme';
	import Icons from '$lib/components/Icons.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import { fade } from 'svelte/transition';
	import {
		getLastTournamentRoute,
		isRememberedTournamentRoute,
		rememberTournamentRoute
	} from '$lib/tournament/navigation';

	let isNavOpen = $state(false);
	let theme = $state('dark');
	let scrolled = $state(false);
	let tournamentLink = $state('/tournament/generator');
	const pathname = $derived(
		$page.url.pathname.endsWith('/') ? $page.url.pathname : `${$page.url.pathname}/`
	);

	$effect(() => {
		theme = initTheme();
		tournamentLink = getLastTournamentRoute();

		const handleScroll = () => {
			scrolled = window.scrollY > 20;
		};

		window.addEventListener('scroll', handleScroll);
		return () => window.removeEventListener('scroll', handleScroll);
	});

	// Keep tournamentLink in sync with routing history
	$effect(() => {
		const pathname = $page.url.pathname;
		if (isRememberedTournamentRoute(pathname)) {
			rememberTournamentRoute(pathname);
			tournamentLink = pathname;
		}
	});

	function handleToggleTheme() {
		theme = toggleTheme();
		if (typeof window !== 'undefined') {
			window.dispatchEvent(new CustomEvent('themeChanged', { detail: { theme } }));
		}
	}

	function closeNav() {
		isNavOpen = false;
	}
</script>

<header
	class={cn(
		'fixed top-0 right-0 left-0 z-[500] transition-all duration-500',
		scrolled
			? 'border-b border-border bg-background/90 py-3 shadow-sm backdrop-blur-md'
			: 'bg-background/70 py-4 backdrop-blur-md'
	)}
>
	<div class="container mx-auto flex h-full max-w-[1200px] items-center justify-between px-6">
		<!-- LOGO -->
		<a href="/" class="group relative z-50 flex min-h-[44px] w-[44px] items-center gap-3 sm:w-auto" onclick={closeNav}>
			<div class="relative">
				<img
					src="/assets/app-icon.jpeg"
					alt="Logo"
					width="40"
					height="40"
					class="h-10 w-10 rounded-xl shadow-lg transition-transform duration-300 group-hover:scale-105"
				/>
				<div
					class="pointer-events-none absolute inset-0 rounded-xl bg-accent/20 opacity-0 transition-opacity group-hover:opacity-100"
				></div>
			</div>
			<span class="hidden font-display text-xl font-black tracking-normal sm:block">
				PADEL<span class="text-accent">COMPANION</span>
			</span>
		</a>

		<!-- DESKTOP NAVIGATION -->
		<nav class="glass hidden items-center gap-1 rounded-xl border border-border p-1 md:flex">
			<a
				href="/#hero"
				onclick={closeNav}
				class="text-foreground-70 hover:bg-secondary hover:text-foreground rounded-lg px-5 py-2.5 font-display text-[10px] font-black tracking-wider uppercase transition-all"
			>
				Home
			</a>

			<a
				href="/#features"
				onclick={closeNav}
				class="text-foreground-70 hover:bg-secondary hover:text-foreground rounded-lg px-5 py-2.5 font-display text-[10px] font-black tracking-wider uppercase transition-all"
			>
				Features
			</a>

			<a
				href="/#tournament-generator"
				onclick={closeNav}
				class="text-foreground-70 hover:bg-secondary hover:text-foreground rounded-lg px-5 py-2.5 font-display text-[10px] font-black tracking-wider uppercase transition-all"
			>
				Tournaments
			</a>

			<a
				href="/#app"
				onclick={closeNav}
				class="text-foreground-70 hover:bg-secondary hover:text-foreground rounded-lg px-5 py-2.5 font-display text-[10px] font-black tracking-wider uppercase transition-all"
			>
				About
			</a>

			<a
				href="/#footer"
				onclick={closeNav}
				class="text-foreground-70 hover:bg-secondary hover:text-foreground rounded-lg px-5 py-2.5 font-display text-[10px] font-black tracking-wider uppercase transition-all"
			>
				Contact
			</a>
		</nav>

		<!-- ACTIONS -->
		<div class="relative z-50 flex items-center gap-4">
			<button
				type="button"
				class="flex h-[44px] w-[44px] cursor-pointer items-center justify-center rounded-xl border border-border bg-secondary text-foreground transition-all hover:bg-secondary/80"
				onclick={handleToggleTheme}
				title="Toggle theme"
				aria-label="Toggle theme"
			>
				{#if theme === 'dark'}
					<Icons name="moon" size={18} />
				{:else}
					<Icons name="sun" size={18} />
				{/if}
			</button>

			<Button href="/#download" variant="primary" size="sm" class="hidden md:inline-flex">
				Get the App
			</Button>

			<!-- Hamburger Menu (Mobile) -->
			<button
				type="button"
				class="flex h-[44px] w-[44px] cursor-pointer flex-col items-center justify-center gap-1 rounded-xl bg-foreground p-2 text-background transition-all active:scale-95 md:hidden"
				onclick={() => (isNavOpen = !isNavOpen)}
				aria-label="Toggle menu"
			>
				<span
					class={cn(
						'block h-0.5 w-5 rounded-full bg-current transition-all duration-300',
						isNavOpen && 'translate-y-1.5 rotate-45'
					)}
				></span>
				<span
					class={cn(
						'block h-0.5 w-5 rounded-full bg-current transition-all duration-300',
						isNavOpen && 'opacity-0'
					)}
				></span>
				<span
					class={cn(
						'block h-0.5 w-5 rounded-full bg-current transition-all duration-300',
						isNavOpen && '-translate-y-1.5 -rotate-45'
					)}
				></span>
			</button>
		</div>
	</div>

	<!-- MOBILE NAVIGATION OVERLAY -->
	{#if isNavOpen}
		<div
			transition:fade={{ duration: 300 }}
			class="fixed inset-0 z-[400] flex flex-col items-center justify-center gap-8 bg-background/95 backdrop-blur-md md:hidden"
		>
			<a
				href="/#hero"
				class="font-display text-4xl font-black tracking-normal uppercase text-foreground opacity-50 hover:opacity-100"
				onclick={closeNav}
			>
				Home
			</a>

			<a
				href="/#features"
				class="font-display text-4xl font-black tracking-normal uppercase text-foreground opacity-50 hover:opacity-100"
				onclick={closeNav}
			>
				Features
			</a>

			<a
				href="/#tournament-generator"
				class="font-display text-4xl font-black tracking-normal uppercase text-foreground opacity-50 hover:opacity-100"
				onclick={closeNav}
			>
				Tournaments
			</a>

			<a
				href="/#app"
				class="font-display text-4xl font-black tracking-normal uppercase text-foreground opacity-50 hover:opacity-100"
				onclick={closeNav}
			>
				About
			</a>

			<a
				href="/#footer"
				class="font-display text-4xl font-black tracking-normal uppercase text-foreground opacity-50 hover:opacity-100"
				onclick={closeNav}
			>
				Contact
			</a>

			<Button href="/#download" variant="primary" size="lg" onclick={closeNav} class="mt-4">
				Get the App
			</Button>

			<!-- Close button for mobile -->
			<button
				type="button"
				onclick={closeNav}
				aria-label="Close menu"
				class="mt-12 flex h-16 w-16 items-center justify-center rounded-full bg-foreground text-3xl font-light text-background transition-transform hover:scale-110"
			>
				&times;
			</button>
		</div>
	{/if}
</header>

// src/components/layout/Header.tsx
import React, { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { initTheme, toggleTheme } from "@/shared/theme";
import {
  getLastTournamentRoute,
  isRememberedTournamentRoute,
  rememberTournamentRoute,
} from "@/tournament/navigation";

const Header: React.FC = () => {
  const [isNavOpen, setIsNavOpen] = useState(false);
  const [theme, setTheme] = useState<string>("dark");
  const [scrolled, setScrolled] = useState(false);
  const [tournamentLink, setTournamentLink] = useState("/tournament/generator");
  const location = useLocation();

  useEffect(() => {
    const currentTheme = initTheme();
    setTheme(currentTheme);
    setTournamentLink(getLastTournamentRoute());

    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    if (!isRememberedTournamentRoute(location.pathname)) {
      return;
    }

    rememberTournamentRoute(location.pathname);
    setTournamentLink(location.pathname);
  }, [location.pathname]);

  const handleToggleTheme = () => {
    const newTheme = toggleTheme();
    setTheme(newTheme);
    window.dispatchEvent(
      new CustomEvent("themeChanged", { detail: { theme: newTheme } })
    );
  };

  const closeNav = () => {
    setIsNavOpen(false);
  };

  const NavLink = ({
    to,
    children,
  }: {
    to: string;
    children: React.ReactNode;
  }) => {
    const isHome = to === "/";
    const isHistory = to === "/tournament/history";
    const isTournament = to === "/tournament/generator";

    let active = false;
    if (isHome && location.pathname === "/") active = true;
    else if (isHistory && location.pathname === "/tournament/history")
      active = true;
    else if (
      isTournament &&
      location.pathname.startsWith("/tournament") &&
      !location.pathname.startsWith("/tournament/history")
    )
      active = true;
    else if (to === "/support" && location.pathname.startsWith("/support"))
      active = true;

    return (
      <Link
        to={to}
        onClick={closeNav}
        className={`text-sm font-medium transition-colors ${
          active
            ? "text-accent font-semibold"
            : "text-muted-foreground hover:text-foreground"
        }`}
      >
        {children}
      </Link>
    );
  };

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-[500] transition-all duration-300 ${
        scrolled
          ? "bg-background/95 backdrop-blur-md border-b border-border py-3"
          : "bg-transparent py-5"
      }`}
    >
      <div className="container max-w-[1200px] mx-auto px-6 h-full flex items-center justify-between">
        {/* LOGO */}
        <Link
          to="/"
          className="flex items-center gap-2 text-xl font-bold text-foreground z-50 relative"
          onClick={closeNav}
        >
          <img
            src="/assets/app-icon.jpeg"
            alt="Padel Companion Logo"
            className="w-9 h-9 rounded-lg"
          />
          <span>Padel Companion</span>
        </Link>

        {/* DESKTOP NAVIGATION */}
        <nav className="hidden md:flex items-center gap-8 absolute left-1/2 -translate-x-1/2">
          <NavLink to="/">Home</NavLink>
          <NavLink to="/tournament/history">History</NavLink>
          <NavLink to={tournamentLink}>Tournament</NavLink>
          <NavLink to="/support">Support</NavLink>
        </nav>

        {/* ACTIONS & MOBILE TOGGLE */}
        <div className="flex items-center gap-3 z-50 relative">
          <button
            className="w-9 h-9 flex items-center justify-center rounded-full bg-card hover:bg-popover transition-colors text-foreground"
            onClick={handleToggleTheme}
            title="Toggle theme"
          >
            <span className="text-lg">{theme === "dark" ? "🌙" : "☀️"}</span>
          </button>

          {/* Hamburger Menu (Mobile) */}
          <button
            className="md:hidden flex h-10 w-10 flex-col items-center justify-center gap-1.5 rounded-full bg-card/80 p-2 text-foreground backdrop-blur-sm"
            onClick={() => setIsNavOpen(!isNavOpen)}
            aria-label="Toggle menu"
            aria-expanded={isNavOpen}
            aria-controls="mobile-navigation"
          >
            <span
              className={`block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300 ${
                isNavOpen ? "rotate-45 translate-y-2" : ""
              }`}
            ></span>
            <span
              className={`block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300 ${
                isNavOpen ? "opacity-0" : ""
              }`}
            ></span>
            <span
              className={`block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300 ${
                isNavOpen ? "-rotate-45 -translate-y-2" : ""
              }`}
            ></span>
          </button>
        </div>
      </div>

      {/* MOBILE NAVIGATION OVERLAY */}
      <div
        id="mobile-navigation"
        className={`fixed inset-0 bg-background z-[400] flex flex-col items-center justify-center gap-8 transition-transform duration-300 md:hidden ${
          isNavOpen ? "translate-x-0" : "translate-x-full"
        }`}
      >
        <button
          type="button"
          onClick={closeNav}
          aria-label="Close menu"
          className="absolute right-6 top-6 flex h-10 w-10 items-center justify-center rounded-full bg-card/80 text-foreground backdrop-blur-sm"
        >
          <span className="text-2xl leading-none">&times;</span>
        </button>
        <Link
          to="/"
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          Home
        </Link>
        <Link
          to="/tournament/history"
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          History
        </Link>
        <Link
          to={tournamentLink}
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          Tournament
        </Link>
        <Link
          to="/support"
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          Support
        </Link>
      </div>
    </header>
  );
};

export default Header;
