// src/components/tournament/PlayerList.tsx
import React, { useState, ReactNode } from "react";
import { StorageService } from "@/shared/storage";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/shared/utils";
import { Dialog } from "@/components/ui/Dialog";
import { Button } from "@/components/ui/Button";

export type ViewMode = "list" | "grid";

export interface PlayerListProps<T extends { name: string }> {
  title?: string;
  singularTitle?: string;
  items: T[];
  onAdd: (name: string) => void;
  onRemove: (index: number) => void;
  onClear?: () => void;
  onImport?: (text: string) => void;
  importTitle?: string;
  importDescription?: ReactNode;
  importPlaceholder?: string;
  onReorder?: (fromIndex: number, toIndex: number) => void;
  renderItem?: (item: T, index: number) => ReactNode;
  renderPrefix?: (item: T, index: number) => ReactNode;
  renderActions?: (item: T, index: number) => ReactNode;
  hintText?: ReactNode;
  maxItems?: number;
  showViewToggle?: boolean;
  defaultView?: ViewMode;
  renderInput?: ReactNode;
}

export function PlayerList<T extends { name: string }>({
  title = "Players",
  singularTitle = "Player",
  items,
  onAdd,
  onRemove,
  onClear,
  onImport,
  importTitle = "Import names",
  importDescription = "Paste one entry per line.",
  importPlaceholder = "Anna\nLisa\nMaja",
  onReorder,
  renderItem,
  renderPrefix,
  renderActions,
  hintText,
  maxItems = 100,
  showViewToggle = true,
  defaultView = "list",
  renderInput,
}: PlayerListProps<T>) {
  const [inputValue, setInputValue] = useState("");
  const [viewMode, setViewMode] = useState<ViewMode>(
    () =>
      (StorageService.getItem("player_list_view", defaultView) as ViewMode) ||
      defaultView,
  );
  const [showAll, setShowAll] = useState(false);
  const [dragIndex, setDragIndex] = useState<number | null>(null);
  const [isImportOpen, setIsImportOpen] = useState(false);
  const [importValue, setImportValue] = useState("");

  const handleAdd = () => {
    const name = inputValue.trim();
    if (!name) return;
    if (items.length >= maxItems) return;
    onAdd(name);
    setInputValue("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      e.preventDefault();
      handleAdd();
    }
  };

  const toggleView = (mode: ViewMode) => {
    setViewMode(mode);
    StorageService.setItem("player_list_view", mode);
  };

  const handleImport = () => {
    if (!onImport) return;
    setIsImportOpen(true);
  };

  const submitImport = () => {
    const text = importValue.trim();
    if (!text || !onImport) return;
    onImport(text);
    setImportValue("");
    setIsImportOpen(false);
  };

  const closeImport = () => {
    setIsImportOpen(false);
    setImportValue("");
  };

  // Drag and drop handlers simplified
  const handleDragStart = (index: number) => setDragIndex(index);

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    if (dragIndex === null || dragIndex === index) return;
  };

  const handleDrop = (index: number) => {
    if (dragIndex === null || dragIndex === index) return;
    if (onReorder) onReorder(dragIndex, index);
    setDragIndex(null);
  };

  const handleDragEnd = () => setDragIndex(null);

  const displayItems = showAll ? items : items.slice(0, 10);
  const hasMore = items.length > 10;

  const defaultItemRenderer = (item: T, index: number) => (
    <motion.li
      layout
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      key={(item as any).id || index}
      className={cn(
        "flex items-center gap-2 py-2 px-3 transition-colors rounded-lg border border-transparent",
        "bg-white/5 hover:bg-white/10 hover:border-white/10",
        dragIndex === index && "opacity-50 ring-2 ring-accent",
      )}
      draggable={!!onReorder}
      onDragStart={() => handleDragStart(index)}
      onDragOver={(e) => handleDragOver(e, index)}
      onDrop={() => handleDrop(index)}
      onDragEnd={handleDragEnd}
    >
      {onReorder && (
        <span
          className="cursor-move text-muted-foreground hover:text-foreground text-xs p-1"
          title="Drag to reorder"
        >
          ⋮⋮
        </span>
      )}

      <span className="text-xs font-mono font-medium text-muted-foreground w-6 text-right">
        {index + 1}.
      </span>

      {renderPrefix && renderPrefix(item, index)}
      <span className="flex-1 font-medium text-foreground truncate text-sm">
        {item.name}
      </span>

      {renderActions && (
        <div className="flex items-center gap-1">
          {renderActions(item, index)}
        </div>
      )}

      <button
        className="w-6 h-6 flex items-center justify-center text-muted-foreground hover:text-error hover:bg-error/10 rounded-full transition-all text-sm"
        onClick={() => onRemove(index)}
        title={`Remove ${item.name}`}
      >
        ×
      </button>
    </motion.li>
  );

  return (
    <div className="space-y-4">
      <Dialog
        isOpen={isImportOpen}
        onClose={closeImport}
        title={importTitle}
        width="lg"
        footer={
          <>
            <Button variant="ghost" onClick={closeImport}>
              Cancel
            </Button>
            <Button onClick={submitImport} disabled={!importValue.trim()}>
              Import
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <div className="text-sm text-muted-foreground">{importDescription}</div>
          <textarea
            className="min-h-56 w-full rounded-xl bg-popover border border-border px-4 py-3 text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent transition-all shadow-sm resize-y"
            placeholder={importPlaceholder}
            value={importValue}
            onChange={(e) => setImportValue(e.target.value)}
          />
        </div>
      </Dialog>

      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-foreground">
          {title}{" "}
          <span className="text-muted-foreground font-normal text-sm bg-muted px-2 py-0.5 rounded-full ml-1">
            {items.length}/{maxItems}
          </span>
        </h3>
        <div className="flex items-center gap-2">
          {onImport && (
            <button
              className="px-3 py-1.5 text-xs font-medium text-muted-foreground hover:text-foreground bg-popover border border-border rounded-lg transition-colors"
              onClick={handleImport}
            >
              Import
            </button>
          )}
          {onClear && items.length > 0 && (
            <button
              className="px-3 py-1.5 text-xs font-medium text-error hover:bg-error/10 border border-error/30 rounded-lg transition-colors"
              onClick={() => {
                if (confirm("Clear all players?")) onClear();
              }}
            >
              Clear
            </button>
          )}
        </div>
      </div>

      {/* Input Row */}
      {renderInput ?? (
        <div className="relative">
          <input
            type="text"
            className="w-full pl-4 pr-20 py-3 rounded-xl bg-popover border border-border text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent transition-all shadow-sm"
            placeholder={`Add ${singularTitle.toLowerCase()}...`}
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={items.length >= maxItems}
          />
          <button
            className="absolute right-1 top-1 bottom-1 px-4 bg-accent hover:bg-accent-dark text-white font-medium rounded-lg transition-colors disabled:opacity-0 disabled:pointer-events-none text-sm"
            onClick={handleAdd}
            disabled={!inputValue.trim() || items.length >= maxItems}
          >
            Add
          </button>
        </div>
      )}

      {/* View Toggle */}
      {showViewToggle && items.length > 0 && (
        <div className="flex justify-end gap-1">
          {/* Using simple buttons for view toggle */}
          <button
            title="List"
            onClick={() => toggleView("list")}
            className={cn(
              "p-1.5 rounded",
              viewMode === "list"
                ? "bg-accent/20 text-accent"
                : "text-muted-foreground",
            )}
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <line x1="8" y1="6" x2="21" y2="6"></line>
              <line x1="8" y1="12" x2="21" y2="12"></line>
              <line x1="8" y1="18" x2="21" y2="18"></line>
              <line x1="3" y1="6" x2="3.01" y2="6"></line>
              <line x1="3" y1="12" x2="3.01" y2="12"></line>
              <line x1="3" y1="18" x2="3.01" y2="18"></line>
            </svg>
          </button>
          <button
            title="Grid"
            onClick={() => toggleView("grid")}
            className={cn(
              "p-1.5 rounded",
              viewMode === "grid"
                ? "bg-accent/20 text-accent"
                : "text-muted-foreground",
            )}
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <rect x="3" y="3" width="7" height="7"></rect>
              <rect x="14" y="3" width="7" height="7"></rect>
              <rect x="14" y="14" width="7" height="7"></rect>
              <rect x="3" y="14" width="7" height="7"></rect>
            </svg>
          </button>
        </div>
      )}

      {/* Items List */}
      <ul
        className={cn(
          "space-y-2",
          viewMode === "grid"
            ? "grid grid-cols-1 sm:grid-cols-2 gap-2 space-y-0"
            : "",
        )}
      >
        <AnimatePresence initial={false} mode="popLayout">
          {displayItems.map((item, idx) =>
            renderItem ? renderItem(item, idx) : defaultItemRenderer(item, idx),
          )}
        </AnimatePresence>
      </ul>

      {/* Show More/Less */}
      {hasMore && (
        <button
          className="w-full py-2 text-center text-xs font-semibold uppercase tracking-wider text-muted-foreground hover:text-accent transition-colors"
          onClick={() => setShowAll(!showAll)}
        >
          {showAll ? "Show Less" : `Show All (${items.length})`}
        </button>
      )}

      {/* Hint */}
      {hintText && (
        <div className="mt-2 text-sm text-center bg-accent/5 border border-accent/10 rounded-lg py-2 px-3">
          {hintText}
        </div>
      )}
    </div>
  );
}

// src/lib/components/tournament/PlayerList.svelte
<script lang="ts">
	import { Dialog } from 'bits-ui';
	import { onMount, type Snippet } from 'svelte';
	import { StorageService } from '$lib/shared/storage';
	import { cn } from '$lib/shared/utils';
	import Icons from '../Icons.svelte';
	import { fade, slide, scale } from 'svelte/transition';
	import { showConfirmModal } from '$lib/tournament/core/modals';
	import Button from '../ui/Button.svelte';

	export type ViewMode = 'list' | 'grid';

	interface Props {
		title?: string;
		singularTitle?: string;
		items: any[];
		onAdd: (name: string) => void;
		onRemove: (index: number) => void;
		onClear?: () => void;
		onImport?: (text: string) => void;
		importTitle?: string;
		importPlaceholder?: string;
		onReorder?: (fromIndex: number, toIndex: number) => void;
		renderActions?: Snippet<[any, number]>;
		hintText?: Snippet;
		maxItems?: number;
		showViewToggle?: boolean;
		defaultView?: ViewMode;
		showDivisions?: boolean;
		onCycleDivision?: (item: any, index: number) => void;
	}

	const {
		title = 'Players',
		singularTitle = 'Player',
		items,
		onAdd,
		onRemove,
		onClear,
		onImport,
		importTitle = 'Import names',
		importPlaceholder = 'Anna\nLisa\nMaja',
		onReorder,
		renderActions,
		hintText,
		maxItems = 100,
		showViewToggle = true,
		defaultView = 'list',
		showDivisions = false,
		onCycleDivision
	}: Props = $props();

	let inputValue = $state('');
	// svelte-ignore state_referenced_locally
	let viewMode = $state<ViewMode>(defaultView);
	let showAll = $state(false);
	let dragIndex = $state<number | null>(null);
	let isImportOpen = $state(false);
	let importValue = $state('');

	onMount(() => {
		viewMode = (StorageService.getItem('player_list_view', defaultView) as ViewMode) || defaultView;
	});

	function handleAdd() {
		const name = inputValue.trim();
		if (!name) return;
		if (items.length >= maxItems) return;
		onAdd(name);
		inputValue = '';
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			e.preventDefault();
			handleAdd();
		}
	}

	function toggleView(mode: ViewMode) {
		viewMode = mode;
		StorageService.setItem('player_list_view', mode);
	}

	function submitImport() {
		const text = importValue.trim();
		if (!text || !onImport) return;
		onImport(text);
		importValue = '';
		isImportOpen = false;
	}

	function closeImport() {
		isImportOpen = false;
		importValue = '';
	}

	// Drag and drop handlers
	function handleDragStart(index: number) {
		dragIndex = index;
	}

	function handleDragOver(e: DragEvent) {
		e.preventDefault();
	}

	function handleDrop(index: number) {
		if (dragIndex === null || dragIndex === index) return;
		if (onReorder) onReorder(dragIndex, index);
		dragIndex = null;
	}

	function handleDragEnd() {
		dragIndex = null;
	}

	const DIVISION_CLASSES: Record<string, string> = {
		A: 'text-[#FF3B30] bg-[#FF3B30]/10 border-[#FF3B30]/20',
		B: 'text-[#42A5F5] bg-[#42A5F5]/10 border-[#42A5F5]/20',
		C: 'text-[#34C759] bg-[#34C759]/10 border-[#34C759]/20',
		D: 'text-[#FFD700] bg-[#FFD700]/10 border-[#FFD700]/20',
		E: 'text-[#AF52DE] bg-[#AF52DE]/10 border-[#AF52DE]/20'
	};

	const displayItems = $derived(showAll ? items : items.slice(0, 16));
	const hasMore = $derived(items.length > 16);
</script>

<div class="relative z-10 space-y-4 font-sans select-none">
	<!-- Header -->
	<div class="flex items-center justify-between border-b border-border pb-3">
		<div class="flex items-center gap-3">
			<h3 class="font-display text-sm font-black tracking-tight text-foreground uppercase">
				{title}
			</h3>
			<div class="group relative">
				<span
					class="rounded-md border border-border bg-foreground/10 px-2 py-0.5 text-[8px] font-black tracking-wider text-foreground uppercase transition-all group-hover:border-accent group-hover:bg-accent"
				>
					{items.length} ACTIVE
				</span>
			</div>
		</div>

		<div class="flex items-center gap-2">
			{#if onImport}
				<button
					type="button"
					class="min-h-[44px] cursor-pointer rounded-lg border border-border bg-foreground/5 px-3 text-[8px] font-black tracking-wider text-foreground/50 uppercase transition-all hover:bg-foreground/10 hover:text-foreground"
					onclick={() => (isImportOpen = true)}
				>
					Import
				</button>
			{/if}
			{#if onClear && items.length > 0}
				<button
					type="button"
					class="min-h-[44px] cursor-pointer rounded-lg border border-[#FF3B30]/10 bg-[#FF3B30]/5 px-3 text-[8px] font-black tracking-wider text-[#FF3B30]/50 uppercase transition-all hover:bg-[#FF3B30]/10 hover:text-[#FF3B30]"
					onclick={() => {
						showConfirmModal(
							'Clear Session',
							'Remove all players from this session?',
							'Clear All',
							() => {
								if (onClear) onClear();
							},
							true
						);
					}}
				>
					Clear
				</button>
			{/if}
		</div>
	</div>

	<!-- Input Row -->
	<div class="group relative">
		<input
			type="text"
			enterkeyhint="done"
			class="min-h-[48px] w-full rounded-xl border border-border bg-foreground/5 py-3 pr-16 pl-4 text-base font-semibold tracking-wider text-foreground shadow-sm transition-all placeholder:text-foreground/30 focus:border-foreground/40 focus:bg-foreground/10 focus:outline-none"
			placeholder={`ADD ${singularTitle.toUpperCase()} NAME...`}
			bind:value={inputValue}
			onkeydown={handleKeyDown}
			disabled={items.length >= maxItems}
		/>
		<div class="absolute top-1 right-1 bottom-1">
			<Button
				variant="shiny"
				size="sm"
				onclick={handleAdd}
				disabled={!inputValue.trim() || items.length >= maxItems}
				class="h-full rounded-lg px-3.5 text-[9px] tracking-wider"
			>
				ADD
			</Button>
		</div>
	</div>

	<!-- View Toggle -->
	{#if showViewToggle && items.length > 0}
		<div class="flex items-center justify-end gap-2">
			<span class="text-[8px] font-black tracking-wider text-foreground/20 uppercase"
				>Display Mode</span
			>
			<div class="flex rounded-lg border border-border bg-foreground/5 p-0.5">
				<button
					type="button"
					aria-label="List View"
					class={cn(
						'flex h-[44px] w-[44px] cursor-pointer items-center justify-center rounded-md p-1 transition-all',
						viewMode === 'list'
							? 'bg-foreground text-background'
							: 'text-foreground/20 hover:text-foreground'
					)}
					onclick={() => toggleView('list')}
				>
					<svg
						width="11"
						height="11"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="3"
						stroke-linecap="round"
					>
						<line x1="8" y1="6" x2="21" y2="6"></line>
						<line x1="8" y1="12" x2="21" y2="12"></line>
						<line x1="8" y1="18" x2="21" y2="18"></line>
						<circle cx="3" cy="6" r="1"></circle>
						<circle cx="3" cy="12" r="1"></circle>
						<circle cx="3" cy="18" r="1"></circle>
					</svg>
				</button>
				<button
					type="button"
					aria-label="Grid View"
					class={cn(
						'flex h-[44px] w-[44px] cursor-pointer items-center justify-center rounded-md p-1 transition-all',
						viewMode === 'grid'
							? 'bg-foreground text-background'
							: 'text-foreground/20 hover:text-foreground'
					)}
					onclick={() => toggleView('grid')}
				>
					<svg
						width="11"
						height="11"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="3"
						stroke-linecap="round"
					>
						<rect x="3" y="3" width="7" height="7"></rect>
						<rect x="14" y="3" width="7" height="7"></rect>
						<rect x="14" y="14" width="7" height="7"></rect>
						<rect x="3" y="14" width="7" height="7"></rect>
					</svg>
				</button>
			</div>
		</div>
	{/if}

	<!-- Items List -->
	<ul
		class={cn(
			'w-full overflow-hidden transition-all duration-300',
			viewMode === 'grid'
				? 'grid grid-cols-1 gap-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-2 xl:grid-cols-3'
				: 'flex flex-col divide-y divide-border/60 rounded-xl border border-border bg-card/30'
		)}
	>
		{#each displayItems as item, idx (item.id || idx)}
			<li
				transition:slide={{ duration: 300 }}
				class={cn(
					'group/item relative flex items-center gap-2 overflow-hidden transition-all duration-300',
					viewMode === 'grid'
						? 'rounded-lg border border-border bg-card/40 px-3 py-1.5 hover:translate-y-0.5 hover:scale-[1.005] hover:border-foreground/20 hover:bg-foreground/10 hover:shadow-lg'
						: 'bg-transparent pl-3.5 pr-4 py-2.5 hover:bg-foreground/5 border-l-2 border-transparent hover:border-l-accent',
					dragIndex === idx
						? viewMode === 'grid'
							? 'border-accent opacity-30'
							: 'bg-accent/10 opacity-30'
						: ''
				)}
				draggable={!!onReorder}
				ondragstart={() => handleDragStart(idx)}
				ondragover={handleDragOver}
				ondrop={() => handleDrop(idx)}
				ondragend={handleDragEnd}
			>
				{#if onReorder}
					<span
						class="cursor-move text-[9px] font-black tracking-wider text-foreground/10 transition-colors select-none group-hover/item:text-accent"
					>
						::
					</span>
				{/if}

				<span
					class="w-4 text-[9px] font-black text-foreground/30 transition-colors group-hover/item:text-foreground/60"
				>
					{(idx + 1).toString().padStart(2, '0')}
				</span>

				<div class="mr-2 flex-1 flex items-center gap-2 min-w-0">
					<span class="text-xs font-black tracking-wider break-words text-foreground truncate">
						{item.name}
					</span>
					{#if showDivisions}
						<button
							type="button"
							onclick={() => onCycleDivision && onCycleDivision(item, idx)}
							class="inline-flex h-[44px] min-w-[44px] shrink-0 cursor-pointer items-center justify-center rounded border px-1.5 text-[8px] font-black uppercase transition-all hover:scale-105 active:scale-95 {DIVISION_CLASSES[item.division || 'A'] || 'text-foreground/60 bg-foreground/5 border-white/5'}"
							title="Click to cycle division"
							aria-label="Cycle division"
						>
							{item.division || 'A'}
						</button>
					{/if}
				</div>

				{#if renderActions}
					<div
						class="flex scale-95 items-center gap-1.5 opacity-0 transition-all group-hover/item:scale-100 group-hover/item:opacity-100"
					>
						{@render renderActions(item, idx)}
					</div>
				{/if}

				<button
					type="button"
					class="flex h-[44px] w-[44px] cursor-pointer items-center justify-center rounded-md border border-transparent text-foreground/40 transition-all hover:border-destructive/10 hover:bg-destructive/10 hover:text-destructive"
					onclick={() => onRemove(idx)}
				>
					<Icons name="trash" size={11} />
				</button>

				<div
					class="pointer-events-none absolute inset-0 bg-gradient-to-r from-foreground/[0.01] to-transparent opacity-0 transition-opacity group-hover/item:opacity-100"
				></div>
			</li>
		{/each}
	</ul>

	<!-- Show More/Less -->
	{#if hasMore}
		<button
			type="button"
			class="mt-3 min-h-[44px] w-full cursor-pointer rounded-lg border border-border bg-foreground/5 py-2.5 text-center text-[9px] font-black tracking-wider text-foreground/50 uppercase transition-all hover:bg-foreground/10 hover:text-foreground"
			onclick={() => (showAll = !showAll)}
		>
			{showAll ? 'COLLAPSE PLAYER LIST' : `EXPAND LIST (+${items.length - 16} MORE)`}
		</button>
	{/if}

	<!-- Hint -->
	{#if hintText}
		<div class="mt-4 rounded-xl border border-border bg-foreground/5 p-3">
			<div class="mb-1 text-[8px] font-black tracking-wider text-accent uppercase">Pro Tip</div>
			<div class="text-[10px] leading-relaxed text-muted-foreground">
				{@render hintText()}
			</div>
		</div>
	{/if}
</div>

<!-- Batch Import Modal -->
<Dialog.Root open={isImportOpen} onOpenChange={(v) => !v && closeImport()}>
	<Dialog.Portal>
		<Dialog.Overlay forceMount>
			{#snippet child({ props, open: isModalOpen })}
				{#if isModalOpen}
					<div
						{...props}
						transition:fade={{ duration: 200 }}
						class="fixed inset-0 z-[800] bg-background/80 backdrop-blur-md"
					></div>
				{/if}
			{/snippet}
		</Dialog.Overlay>
		<Dialog.Content forceMount>
			{#snippet child({ props, open: isModalOpen })}
				{#if isModalOpen}
					<div
						{...props}
						transition:scale={{ duration: 220, start: 0.97, opacity: 0 }}
						class="fixed top-1/2 left-1/2 z-[801] max-h-[90dvh] w-full max-w-xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto overscroll-contain rounded-card border border-border bg-popover p-6 shadow-lg md:p-8"
					>
						<Dialog.Title
							class="mb-2 font-display text-2xl font-black tracking-normal text-foreground"
						>
							{importTitle}
						</Dialog.Title>
						<p class="mb-6 text-xs font-black tracking-wider text-muted-foreground uppercase">
							Fast batch entry
						</p>

						<div class="mb-6 space-y-4">
							<textarea
								enterkeyhint="done"
								class="min-h-[300px] w-full resize-none rounded-xl border border-border bg-foreground/[0.03] p-5 text-sm font-semibold tracking-normal text-foreground transition-all placeholder:text-foreground/25 focus:border-accent focus:outline-none md:p-6"
								placeholder={importPlaceholder}
								bind:value={importValue}
							></textarea>
							<p class="text-center text-[10px] tracking-wider text-muted-foreground">
								Tip: Paste from WhatsApp, Excel or Notes. One name per line.
							</p>
						</div>

						<div class="flex items-center gap-4">
							<Button variant="ghost" size="lg" onclick={closeImport} class="flex-1">Cancel</Button>
							<Button
								variant="shiny"
								size="lg"
								onclick={submitImport}
								disabled={!importValue.trim()}
								class="flex-[2]"
							>
								START IMPORT
							</Button>
						</div>
					</div>
				{/if}
			{/snippet}
		</Dialog.Content>
	</Dialog.Portal>
</Dialog.Root>
