// src/components/layout/Header.tsx
import React, { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { initTheme, toggleTheme } from "@/shared/theme";
import {
  getLastTournamentRoute,
  isRememberedTournamentRoute,
  rememberTournamentRoute,
} from "@/tournament/navigation";

const Header: React.FC = () => {
  const [isNavOpen, setIsNavOpen] = useState(false);
  const [theme, setTheme] = useState<string>("dark");
  const [scrolled, setScrolled] = useState(false);
  const [tournamentLink, setTournamentLink] = useState("/tournament/generator");
  const location = useLocation();

  useEffect(() => {
    const currentTheme = initTheme();
    setTheme(currentTheme);
    setTournamentLink(getLastTournamentRoute());

    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    if (!isRememberedTournamentRoute(location.pathname)) {
      return;
    }

    rememberTournamentRoute(location.pathname);
    setTournamentLink(location.pathname);
  }, [location.pathname]);

  const handleToggleTheme = () => {
    const newTheme = toggleTheme();
    setTheme(newTheme);
    window.dispatchEvent(
      new CustomEvent("themeChanged", { detail: { theme: newTheme } })
    );
  };

  const closeNav = () => {
    setIsNavOpen(false);
  };

  const NavLink = ({
    to,
    children,
  }: {
    to: string;
    children: React.ReactNode;
  }) => {
    const isHome = to === "/";
    const isHistory = to === "/tournament/history";
    const isTournament = to === "/tournament/generator";

    let active = false;
    if (isHome && location.pathname === "/") active = true;
    else if (isHistory && location.pathname === "/tournament/history")
      active = true;
    else if (
      isTournament &&
      location.pathname.startsWith("/tournament") &&
      !location.pathname.startsWith("/tournament/history")
    )
      active = true;
    else if (to === "/support" && location.pathname.startsWith("/support"))
      active = true;

    return (
      <Link
        to={to}
        onClick={closeNav}
        className={`text-sm font-medium transition-colors ${
          active
            ? "text-accent font-semibold"
            : "text-muted-foreground hover:text-foreground"
        }`}
      >
        {children}
      </Link>
    );
  };

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-[500] transition-all duration-300 ${
        scrolled
          ? "bg-background/95 backdrop-blur-md border-b border-border py-3"
          : "bg-transparent py-5"
      }`}
    >
      <div className="container max-w-[1200px] mx-auto px-6 h-full flex items-center justify-between">
        {/* LOGO */}
        <Link
          to="/"
          className="flex items-center gap-2 text-xl font-bold text-foreground z-50 relative"
          onClick={closeNav}
        >
          <img
            src="/assets/app-icon.jpeg"
            alt="Padel Companion Logo"
            className="w-9 h-9 rounded-lg"
          />
          <span>Padel Companion</span>
        </Link>

        {/* DESKTOP NAVIGATION */}
        <nav className="hidden md:flex items-center gap-8 absolute left-1/2 -translate-x-1/2">
          <NavLink to="/">Home</NavLink>
          <NavLink to="/tournament/history">History</NavLink>
          <NavLink to={tournamentLink}>Tournament</NavLink>
          <NavLink to="/support">Support</NavLink>
        </nav>

        {/* ACTIONS & MOBILE TOGGLE */}
        <div className="flex items-center gap-3 z-50 relative">
          <button
            className="w-9 h-9 flex items-center justify-center rounded-full bg-card hover:bg-popover transition-colors text-foreground"
            onClick={handleToggleTheme}
            title="Toggle theme"
          >
            <span className="text-lg">{theme === "dark" ? "🌙" : "☀️"}</span>
          </button>

          {/* Hamburger Menu (Mobile) */}
          <button
            className="md:hidden flex h-10 w-10 flex-col items-center justify-center gap-1.5 rounded-full bg-card/80 p-2 text-foreground backdrop-blur-sm"
            onClick={() => setIsNavOpen(!isNavOpen)}
            aria-label="Toggle menu"
            aria-expanded={isNavOpen}
            aria-controls="mobile-navigation"
          >
            <span
              className={`block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300 ${
                isNavOpen ? "rotate-45 translate-y-2" : ""
              }`}
            ></span>
            <span
              className={`block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300 ${
                isNavOpen ? "opacity-0" : ""
              }`}
            ></span>
            <span
              className={`block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300 ${
                isNavOpen ? "-rotate-45 -translate-y-2" : ""
              }`}
            ></span>
          </button>
        </div>
      </div>

      {/* MOBILE NAVIGATION OVERLAY */}
      <div
        id="mobile-navigation"
        className={`fixed inset-0 bg-background z-[400] flex flex-col items-center justify-center gap-8 transition-transform duration-300 md:hidden ${
          isNavOpen ? "translate-x-0" : "translate-x-full"
        }`}
      >
        <button
          type="button"
          onClick={closeNav}
          aria-label="Close menu"
          className="absolute right-6 top-6 flex h-10 w-10 items-center justify-center rounded-full bg-card/80 text-foreground backdrop-blur-sm"
        >
          <span className="text-2xl leading-none">&times;</span>
        </button>
        <Link
          to="/"
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          Home
        </Link>
        <Link
          to="/tournament/history"
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          History
        </Link>
        <Link
          to={tournamentLink}
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          Tournament
        </Link>
        <Link
          to="/support"
          className="text-2xl font-medium text-foreground"
          onClick={closeNav}
        >
          Support
        </Link>
      </div>
    </header>
  );
};

export default Header;

// padelcompanion-svelte/src/lib/components/Header.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { cn } from "$lib/shared/utils";
  import { initTheme, toggleTheme } from "$lib/shared/theme";
  import Icons from "$lib/components/Icons.svelte";
  import {
    getLastTournamentRoute,
    isRememberedTournamentRoute,
    rememberTournamentRoute,
  } from "$lib/tournament/navigation";

  let isNavOpen = $state(false);
  let theme = $state("dark");
  let scrolled = $state(false);
  let tournamentLink = $state("/tournament/generator");

  $effect(() => {
    theme = initTheme();
    tournamentLink = getLastTournamentRoute();

    const handleScroll = () => {
      scrolled = window.scrollY > 20;
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  });

  // Keep tournamentLink in sync with routing history
  $effect(() => {
    const pathname = $page.url.pathname;
    if (isRememberedTournamentRoute(pathname)) {
      rememberTournamentRoute(pathname);
      tournamentLink = pathname;
    }
  });

  function handleToggleTheme() {
    theme = toggleTheme();
    if (typeof window !== "undefined") {
      window.dispatchEvent(
        new CustomEvent("themeChanged", { detail: { theme } })
      );
    }
  }

  function closeNav() {
    isNavOpen = false;
  }
</script>

<header
  class={cn(
    "fixed top-0 left-0 right-0 z-[500] transition-all duration-300",
    scrolled
      ? "bg-background/95 backdrop-blur-md border-b border-border py-3"
      : "bg-transparent py-5"
  )}
>
  <div class="container max-w-[1200px] mx-auto px-6 h-full flex items-center justify-between">
    <!-- LOGO -->
    <a
      href="/"
      class="flex items-center gap-2 text-xl font-bold text-foreground z-50 relative font-display"
      onclick={closeNav}
    >
      <img
        src="/assets/app-icon.jpeg"
        alt="Padel Companion Logo"
        width="36"
        height="36"
        class="w-9 h-9 rounded-lg"
      />
      <span>Padel Companion</span>
    </a>

    <!-- DESKTOP NAVIGATION -->
    <nav class="hidden md:flex items-center gap-8 absolute left-1/2 -translate-x-1/2">
      <!-- Home Link -->
      <a
        href="/"
        onclick={closeNav}
        class={cn(
          "text-sm font-medium transition-colors font-display",
          $page.url.pathname === "/"
            ? "text-accent font-semibold"
            : "text-muted-foreground hover:text-foreground"
        )}
      >
        Home
      </a>

      <!-- History Link -->
      <a
        href="/tournament/history"
        onclick={closeNav}
        class={cn(
          "text-sm font-medium transition-colors font-display",
          ($page.url.pathname as string) === "/tournament/history"
            ? "text-accent font-semibold"
            : "text-muted-foreground hover:text-foreground"
        )}
      >
        History
      </a>

      <!-- Tournament Link -->
      <a
        href={tournamentLink}
        onclick={closeNav}
        class={cn(
          "text-sm font-medium transition-colors font-display",
          ($page.url.pathname as string).startsWith("/tournament") && !($page.url.pathname as string).startsWith("/tournament/history")
            ? "text-accent font-semibold"
            : "text-muted-foreground hover:text-foreground"
        )}
      >
        Tournament
      </a>

      <!-- Support Link -->
      <a
        href="/support"
        onclick={closeNav}
        class={cn(
          "text-sm font-medium transition-colors font-display",
          $page.url.pathname === "/support"
            ? "text-accent font-semibold"
            : "text-muted-foreground hover:text-foreground"
        )}
      >
        Support
      </a>
    </nav>

    <!-- ACTIONS & MOBILE TOGGLE -->
    <div class="flex items-center gap-3 z-50 relative">
      <button
        class="w-9 h-9 flex items-center justify-center rounded-full bg-card hover:bg-popover transition-colors text-foreground cursor-pointer"
        onclick={handleToggleTheme}
        title="Toggle theme"
      >
        <span class="flex items-center text-foreground">
          {#if theme === "dark"}
            <Icons name="moon" size={18} />
          {:else}
            <Icons name="sun" size={18} />
          {/if}
        </span>
      </button>

      <!-- Hamburger Menu (Mobile) -->
      <button
        class="md:hidden flex h-10 w-10 flex-col items-center justify-center gap-1.5 rounded-full bg-card/80 p-2 text-foreground backdrop-blur-sm cursor-pointer"
        onclick={() => (isNavOpen = !isNavOpen)}
        aria-label="Toggle menu"
        aria-expanded={isNavOpen}
        aria-controls="mobile-navigation"
      >
        <span
          class={cn(
            "block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300",
            isNavOpen && "rotate-45 translate-y-2"
          )}
        ></span>
        <span
          class={cn(
            "block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300",
            isNavOpen && "opacity-0"
          )}
        ></span>
        <span
          class={cn(
            "block h-0.5 w-6 rounded-full bg-foreground transition-all duration-300",
            isNavOpen && "-rotate-45 -translate-y-2"
          )}
        ></span>
      </button>
    </div>
  </div>

  <!-- MOBILE NAVIGATION OVERLAY -->
  <div
    id="mobile-navigation"
    class={cn(
      "fixed inset-0 bg-background z-[400] flex flex-col items-center justify-center gap-8 transition-transform duration-300 md:hidden",
      isNavOpen ? "translate-x-0" : "translate-x-full"
    )}
  >
    <button
      type="button"
      onclick={closeNav}
      aria-label="Close menu"
      class="absolute right-6 top-6 flex h-10 w-10 items-center justify-center rounded-full bg-card/80 text-foreground backdrop-blur-sm cursor-pointer"
    >
      <span class="text-2xl leading-none">&times;</span>
    </button>
    
    <a
      href="/"
      class={cn(
        "text-2xl font-medium transition-colors font-display",
        $page.url.pathname === "/" ? "text-accent font-bold" : "text-foreground"
      )}
      onclick={closeNav}
    >
      Home
    </a>
    
    <a
      href="/tournament/history"
      class={cn(
        "text-2xl font-medium transition-colors font-display",
        ($page.url.pathname as string) === "/tournament/history" ? "text-accent font-bold" : "text-foreground"
      )}
      onclick={closeNav}
    >
      History
    </a>
    
    <a
      href={tournamentLink}
      class={cn(
        "text-2xl font-medium transition-colors font-display",
        ($page.url.pathname as string).startsWith("/tournament") && !($page.url.pathname as string).startsWith("/tournament/history")
          ? "text-accent font-bold"
          : "text-foreground"
      )}
      onclick={closeNav}
    >
      Tournament
    </a>
    
    <a
      href="/support"
      class={cn(
        "text-2xl font-medium transition-colors font-display",
        $page.url.pathname === "/support" ? "text-accent font-bold" : "text-foreground"
      )}
      onclick={closeNav}
    >
      Support
    </a>
  </div>
</header>
