// padelcompanion-svelte/src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "$lib/shared/utils";

  type Variant = "primary" | "secondary" | "accent" | "ghost";
  type Size = "sm" | "md" | "lg";

  interface Props {
    href?: string;
    variant?: Variant;
    size?: Size;
    type?: "button" | "submit" | "reset";
    disabled?: boolean;
    onclick?: (e: MouseEvent) => void;
    class?: string;
    children: Snippet;
    target?: string;
    rel?: string;
  }

  let {
    href,
    variant = "primary",
    size = "md",
    type = "button",
    disabled = false,
    onclick,
    class: klass = "",
    children,
    target,
    rel,
  }: Props = $props();

  const base = "inline-flex items-center justify-center rounded-full font-bold transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed";

  const variants: Record<Variant, string> = {
    primary: "bg-foreground text-background hover:bg-foreground/90 shadow-lg hover-glow",
    secondary: "bg-card hover:bg-popover border border-border text-foreground shadow-md",
    accent: "bg-accent hover:bg-accent-hover text-white shadow-lg shadow-accent/20",
    ghost: "bg-transparent hover:bg-white/5 text-foreground",
  };

  const sizes: Record<Size, string> = {
    sm: "px-4 py-2 text-sm",
    md: "px-6 py-3 text-base",
    lg: "px-8 py-4 text-lg",
  };

  let cls = $derived(cn(base, variants[variant], sizes[size], klass));
</script>

{#if href}
  <a {href} class={cls} {target} {rel}>{@render children()}</a>
{:else}
  <button {type} {disabled} {onclick} class={cls}>{@render children()}</button>
{/if}

// src/components/ui/Button.tsx
import React from "react";
import { cn } from "@/shared/utils";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "danger" | "ghost";
  size?: "sm" | "md" | "lg";
  fullWidth?: boolean;
}

const variantClasses = {
  primary:
    "bg-accent hover:bg-accent-dark text-primary-foreground shadow-sm hover:shadow-md",
  secondary:
    "bg-card hover:bg-popover border border-border text-foreground hover:border-accent/50",
  danger: "bg-error/10 hover:bg-error/20 text-error border border-error/30",
  ghost: "bg-transparent hover:bg-surface-hover text-muted-foreground hover:text-foreground",
};

const sizeClasses = {
  sm: "px-3 py-1.5 text-sm rounded-lg",
  md: "px-4 py-2.5 text-base rounded-xl",
  lg: "px-6 py-3 text-lg rounded-xl",
};

/**
 * Standardized Button component with Tailwind styling.
 */
export const Button: React.FC<ButtonProps> = ({
  children,
  variant = "primary",
  size = "md",
  fullWidth = false,
  className = "",
  disabled,
  ...props
}) => {
  const classes = cn(
    "font-medium transition-all duration-200 inline-flex items-center justify-center gap-2",
    variantClasses[variant],
    sizeClasses[size],
    fullWidth && "w-full",
    disabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer",
    className,
  );

  return (
    <button className={classes} disabled={disabled} {...props}>
      {children}
    </button>
  );
};
