// src/lib/components/ui/GlassCard.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/shared/utils';

	interface Props {
		children: Snippet;
		variant?: 'default' | 'hover' | 'active' | 'premium';
		padding?: 'none' | 'sm' | 'md' | 'lg';
		withNoise?: boolean;
		class?: string;
		[key: string]: any;
	}

	const {
		children,
		variant = 'default',
		padding = 'md',
		withNoise = true,
		class: klass = '',
		...props
	}: Props = $props();

	const variants = {
		default: 'glass',
		premium: 'glass-premium',
		hover:
			'glass hover:border-accent/20 hover:shadow-[0_14px_34px_rgba(0,122,255,0.08)] hover:scale-[1.01] transition-all duration-300',
		active:
			'border border-accent/20 bg-accent/5 backdrop-blur-md shadow-[0_12px_28px_rgba(0,122,255,0.1)]'
	};

	const paddingClasses = {
		none: 'p-0',
		sm: 'p-4',
		md: 'p-6 md:p-8',
		lg: 'p-8 md:p-12'
	};
</script>

<div
	class={cn(
		'relative overflow-hidden rounded-card transition-all duration-300',
		variants[variant],
		paddingClasses[padding],
		withNoise && 'noise',
		klass
	)}
	{...props}
>
	<!-- Subtle top light for depth -->
	<div
		class="pointer-events-none absolute inset-x-0 top-0 z-20 h-px bg-gradient-to-r from-transparent via-foreground/10 to-transparent"
	></div>

	<div class="relative z-10">
		{@render children()}
	</div>
</div>

// src/components/ui/GlassCard.tsx
import React from "react";
import { motion, HTMLMotionProps } from "framer-motion";
import { cn } from "@/shared/utils"; // Assuming utils exists, or I need to create it

interface GlassCardProps extends HTMLMotionProps<"div"> {
  children: React.ReactNode;
  variant?: "default" | "hover" | "active";
  padding?: "none" | "sm" | "md" | "lg";
}

const variants = {
  default: "bg-glass-background backdrop-blur-md border border-glass-border shadow-lg",
  hover:
    "bg-glass-background backdrop-blur-md border border-glass-border shadow-lg hover:border-accent/30 hover:shadow-xl transition-all duration-300",
  active:
    "bg-accent/20 backdrop-blur-md border border-accent/50 shadow-[0_0_15px_rgba(59,130,246,0.2)]",
};

const paddingClasses = {
  none: "p-0",
  sm: "p-3",
  md: "p-6",
  lg: "p-8",
};

export const GlassCard: React.FC<GlassCardProps> = ({
  children,
  className,
  variant = "default",
  padding = "md",
  ...props
}) => {
  return (
    <motion.div
      className={cn(
        "rounded-2xl relative overflow-hidden",
        variants[variant],
        paddingClasses[padding],
        className,
      )}
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 10 }}
      transition={{ duration: 0.3 }}
      {...props}
    >
      {/* Noise Texture Overlay (Optional, adds premium feel) */}
      <div className="absolute inset-0 opacity-[0.03] pointer-events-none bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />

      {/* Content */}
      <div className="relative z-10">{children}</div>
    </motion.div>
  );
};
